/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BaseResponse } from '../models';
// @ts-ignore
import type { DealerStatus } from '../models';
// @ts-ignore
import type { DeleteMarketInstrument200Response } from '../models';
// @ts-ignore
import type { FermataArchiveDealerRequest } from '../models';
// @ts-ignore
import type { FermataCloseWalletRequest } from '../models';
// @ts-ignore
import type { FermataCreateDealer200Response } from '../models';
// @ts-ignore
import type { FermataCreateDealerRequest } from '../models';
// @ts-ignore
import type { FermataCreateWallet200Response } from '../models';
// @ts-ignore
import type { FermataCreateWalletRequest } from '../models';
// @ts-ignore
import type { FermataFreezeWalletRequest } from '../models';
// @ts-ignore
import type { FermataLinkDealerRequest } from '../models';
// @ts-ignore
import type { FermataListDealers200Response } from '../models';
// @ts-ignore
import type { FermataListWallets200Response } from '../models';
// @ts-ignore
import type { FermataPauseDealerRequest } from '../models';
// @ts-ignore
import type { FermataResumeDealerRequest } from '../models';
// @ts-ignore
import type { FermataTransferWalletRequest } from '../models';
// @ts-ignore
import type { FermataUnfreezeWalletRequest } from '../models';
// @ts-ignore
import type { FermataUnlinkDealerRequest } from '../models';
// @ts-ignore
import type { WalletType } from '../models';
/**
 * FermataApi - axios parameter creator
 */
export const FermataApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Archive a dealer — permanently stops all operations. All open positions must be closed before archiving. Admin only.
         * @summary Archive dealer
         * @param {FermataArchiveDealerRequest} [fermataArchiveDealerRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataArchiveDealer: async (fermataArchiveDealerRequest?: FermataArchiveDealerRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/fermata/dealer/archive`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(fermataArchiveDealerRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Close a wallet. Terminal state — only a final withdrawal to zero balance is allowed after closing.
         * @summary Close wallet
         * @param {FermataCloseWalletRequest} [fermataCloseWalletRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataCloseWallet: async (fermataCloseWalletRequest?: FermataCloseWalletRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/fermata/wallet/close`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(fermataCloseWalletRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a new dealer account in the Fermata venue. Admin only. Provisions a Trading Account (venue=FERMATA), a dealer wallet in the Formance Ledger, and dealer configuration.
         * @summary Create dealer
         * @param {FermataCreateDealerRequest} [fermataCreateDealerRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataCreateDealer: async (fermataCreateDealerRequest?: FermataCreateDealerRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/fermata/dealer/create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(fermataCreateDealerRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a new wallet in the Fermata ledger.
         * @summary Create wallet
         * @param {FermataCreateWalletRequest} [fermataCreateWalletRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataCreateWallet: async (fermataCreateWalletRequest?: FermataCreateWalletRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/fermata/wallet/create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(fermataCreateWalletRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Freeze a wallet, blocking all transactions. Admin only.
         * @summary Freeze wallet
         * @param {FermataFreezeWalletRequest} [fermataFreezeWalletRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataFreezeWallet: async (fermataFreezeWalletRequest?: FermataFreezeWalletRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/fermata/wallet/freeze`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(fermataFreezeWalletRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a single dealer by ID, including configuration and linked accounts.
         * @summary Get dealer
         * @param {string} dealerAccountId Dealer account ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataGetDealer: async (dealerAccountId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'dealerAccountId' is not null or undefined
            assertParamExists('fermataGetDealer', 'dealerAccountId', dealerAccountId)
            const localVarPath = `/api/v3/fermata/dealer/get`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (dealerAccountId !== undefined) {
                localVarQueryParameter['dealerAccountId'] = dealerAccountId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get a single wallet by ID, including balances and status.
         * @summary Get wallet
         * @param {string} walletId Wallet ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataGetWallet: async (walletId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'walletId' is not null or undefined
            assertParamExists('fermataGetWallet', 'walletId', walletId)
            const localVarPath = `/api/v3/fermata/wallet/get`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (walletId !== undefined) {
                localVarQueryParameter['walletId'] = walletId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Link an existing exchange trading account to the dealer as a liquidity provider for hedging.
         * @summary Link exchange account to dealer
         * @param {FermataLinkDealerRequest} [fermataLinkDealerRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataLinkDealer: async (fermataLinkDealerRequest?: FermataLinkDealerRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/fermata/dealer/link`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(fermataLinkDealerRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List dealers with optional status filter. Admin only.
         * @summary List dealers
         * @param {DealerStatus} [status] Filter by dealer status
         * @param {number} [limit] Limit the number of returned results
         * @param {number} [offset] Offset of the returned results
         * @param {string} [cursor] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataListDealers: async (status?: DealerStatus, limit?: number, offset?: number, cursor?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/fermata/dealer/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List wallets by type, owner, or dealer.
         * @summary List wallets
         * @param {WalletType} [walletType] Filter by wallet type
         * @param {number} [limit] Limit the number of returned results
         * @param {number} [offset] Offset of the returned results
         * @param {string} [cursor] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataListWallets: async (walletType?: WalletType, limit?: number, offset?: number, cursor?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/fermata/wallet/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (walletType !== undefined) {
                localVarQueryParameter['walletType'] = walletType;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Pause a dealer — stops quoting but continues hedging open positions. Admin only.
         * @summary Pause dealer
         * @param {FermataPauseDealerRequest} [fermataPauseDealerRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataPauseDealer: async (fermataPauseDealerRequest?: FermataPauseDealerRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/fermata/dealer/pause`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(fermataPauseDealerRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Resume a paused dealer — restores quoting capability. Admin only.
         * @summary Resume dealer
         * @param {FermataResumeDealerRequest} [fermataResumeDealerRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataResumeDealer: async (fermataResumeDealerRequest?: FermataResumeDealerRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/fermata/dealer/resume`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(fermataResumeDealerRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Transfer assets between wallets owned by the same user under the same dealer.
         * @summary Transfer between wallets
         * @param {FermataTransferWalletRequest} [fermataTransferWalletRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataTransferWallet: async (fermataTransferWalletRequest?: FermataTransferWalletRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/fermata/wallet/transfer`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(fermataTransferWalletRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Unfreeze a previously frozen wallet, restoring transaction capabilities. Admin only.
         * @summary Unfreeze wallet
         * @param {FermataUnfreezeWalletRequest} [fermataUnfreezeWalletRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataUnfreezeWallet: async (fermataUnfreezeWalletRequest?: FermataUnfreezeWalletRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/fermata/wallet/unfreeze`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(fermataUnfreezeWalletRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Unlink an exchange trading account from the dealer.
         * @summary Unlink exchange account from dealer
         * @param {FermataUnlinkDealerRequest} [fermataUnlinkDealerRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataUnlinkDealer: async (fermataUnlinkDealerRequest?: FermataUnlinkDealerRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/fermata/dealer/unlink`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(fermataUnlinkDealerRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FermataApi - functional programming interface
 */
export const FermataApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FermataApiAxiosParamCreator(configuration)
    return {
        /**
         * Archive a dealer — permanently stops all operations. All open positions must be closed before archiving. Admin only.
         * @summary Archive dealer
         * @param {FermataArchiveDealerRequest} [fermataArchiveDealerRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fermataArchiveDealer(fermataArchiveDealerRequest?: FermataArchiveDealerRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FermataCreateDealer200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fermataArchiveDealer(fermataArchiveDealerRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FermataApi.fermataArchiveDealer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Close a wallet. Terminal state — only a final withdrawal to zero balance is allowed after closing.
         * @summary Close wallet
         * @param {FermataCloseWalletRequest} [fermataCloseWalletRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fermataCloseWallet(fermataCloseWalletRequest?: FermataCloseWalletRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FermataCreateWallet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fermataCloseWallet(fermataCloseWalletRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FermataApi.fermataCloseWallet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create a new dealer account in the Fermata venue. Admin only. Provisions a Trading Account (venue=FERMATA), a dealer wallet in the Formance Ledger, and dealer configuration.
         * @summary Create dealer
         * @param {FermataCreateDealerRequest} [fermataCreateDealerRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fermataCreateDealer(fermataCreateDealerRequest?: FermataCreateDealerRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FermataCreateDealer200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fermataCreateDealer(fermataCreateDealerRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FermataApi.fermataCreateDealer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create a new wallet in the Fermata ledger.
         * @summary Create wallet
         * @param {FermataCreateWalletRequest} [fermataCreateWalletRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fermataCreateWallet(fermataCreateWalletRequest?: FermataCreateWalletRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FermataCreateWallet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fermataCreateWallet(fermataCreateWalletRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FermataApi.fermataCreateWallet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Freeze a wallet, blocking all transactions. Admin only.
         * @summary Freeze wallet
         * @param {FermataFreezeWalletRequest} [fermataFreezeWalletRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fermataFreezeWallet(fermataFreezeWalletRequest?: FermataFreezeWalletRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FermataCreateWallet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fermataFreezeWallet(fermataFreezeWalletRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FermataApi.fermataFreezeWallet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get a single dealer by ID, including configuration and linked accounts.
         * @summary Get dealer
         * @param {string} dealerAccountId Dealer account ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fermataGetDealer(dealerAccountId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FermataCreateDealer200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fermataGetDealer(dealerAccountId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FermataApi.fermataGetDealer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get a single wallet by ID, including balances and status.
         * @summary Get wallet
         * @param {string} walletId Wallet ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fermataGetWallet(walletId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FermataCreateWallet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fermataGetWallet(walletId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FermataApi.fermataGetWallet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Link an existing exchange trading account to the dealer as a liquidity provider for hedging.
         * @summary Link exchange account to dealer
         * @param {FermataLinkDealerRequest} [fermataLinkDealerRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fermataLinkDealer(fermataLinkDealerRequest?: FermataLinkDealerRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeleteMarketInstrument200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fermataLinkDealer(fermataLinkDealerRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FermataApi.fermataLinkDealer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List dealers with optional status filter. Admin only.
         * @summary List dealers
         * @param {DealerStatus} [status] Filter by dealer status
         * @param {number} [limit] Limit the number of returned results
         * @param {number} [offset] Offset of the returned results
         * @param {string} [cursor] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fermataListDealers(status?: DealerStatus, limit?: number, offset?: number, cursor?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FermataListDealers200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fermataListDealers(status, limit, offset, cursor, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FermataApi.fermataListDealers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List wallets by type, owner, or dealer.
         * @summary List wallets
         * @param {WalletType} [walletType] Filter by wallet type
         * @param {number} [limit] Limit the number of returned results
         * @param {number} [offset] Offset of the returned results
         * @param {string} [cursor] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fermataListWallets(walletType?: WalletType, limit?: number, offset?: number, cursor?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FermataListWallets200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fermataListWallets(walletType, limit, offset, cursor, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FermataApi.fermataListWallets']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Pause a dealer — stops quoting but continues hedging open positions. Admin only.
         * @summary Pause dealer
         * @param {FermataPauseDealerRequest} [fermataPauseDealerRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fermataPauseDealer(fermataPauseDealerRequest?: FermataPauseDealerRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FermataCreateDealer200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fermataPauseDealer(fermataPauseDealerRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FermataApi.fermataPauseDealer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Resume a paused dealer — restores quoting capability. Admin only.
         * @summary Resume dealer
         * @param {FermataResumeDealerRequest} [fermataResumeDealerRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fermataResumeDealer(fermataResumeDealerRequest?: FermataResumeDealerRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FermataCreateDealer200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fermataResumeDealer(fermataResumeDealerRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FermataApi.fermataResumeDealer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Transfer assets between wallets owned by the same user under the same dealer.
         * @summary Transfer between wallets
         * @param {FermataTransferWalletRequest} [fermataTransferWalletRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fermataTransferWallet(fermataTransferWalletRequest?: FermataTransferWalletRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeleteMarketInstrument200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fermataTransferWallet(fermataTransferWalletRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FermataApi.fermataTransferWallet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Unfreeze a previously frozen wallet, restoring transaction capabilities. Admin only.
         * @summary Unfreeze wallet
         * @param {FermataUnfreezeWalletRequest} [fermataUnfreezeWalletRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fermataUnfreezeWallet(fermataUnfreezeWalletRequest?: FermataUnfreezeWalletRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FermataCreateWallet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fermataUnfreezeWallet(fermataUnfreezeWalletRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FermataApi.fermataUnfreezeWallet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Unlink an exchange trading account from the dealer.
         * @summary Unlink exchange account from dealer
         * @param {FermataUnlinkDealerRequest} [fermataUnlinkDealerRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fermataUnlinkDealer(fermataUnlinkDealerRequest?: FermataUnlinkDealerRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeleteMarketInstrument200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fermataUnlinkDealer(fermataUnlinkDealerRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FermataApi.fermataUnlinkDealer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FermataApi - factory interface
 */
export const FermataApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FermataApiFp(configuration)
    return {
        /**
         * Archive a dealer — permanently stops all operations. All open positions must be closed before archiving. Admin only.
         * @summary Archive dealer
         * @param {FermataArchiveDealerRequest} [fermataArchiveDealerRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataArchiveDealer(fermataArchiveDealerRequest?: FermataArchiveDealerRequest, options?: RawAxiosRequestConfig): AxiosPromise<FermataCreateDealer200Response> {
            return localVarFp.fermataArchiveDealer(fermataArchiveDealerRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Close a wallet. Terminal state — only a final withdrawal to zero balance is allowed after closing.
         * @summary Close wallet
         * @param {FermataCloseWalletRequest} [fermataCloseWalletRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataCloseWallet(fermataCloseWalletRequest?: FermataCloseWalletRequest, options?: RawAxiosRequestConfig): AxiosPromise<FermataCreateWallet200Response> {
            return localVarFp.fermataCloseWallet(fermataCloseWalletRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a new dealer account in the Fermata venue. Admin only. Provisions a Trading Account (venue=FERMATA), a dealer wallet in the Formance Ledger, and dealer configuration.
         * @summary Create dealer
         * @param {FermataCreateDealerRequest} [fermataCreateDealerRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataCreateDealer(fermataCreateDealerRequest?: FermataCreateDealerRequest, options?: RawAxiosRequestConfig): AxiosPromise<FermataCreateDealer200Response> {
            return localVarFp.fermataCreateDealer(fermataCreateDealerRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a new wallet in the Fermata ledger.
         * @summary Create wallet
         * @param {FermataCreateWalletRequest} [fermataCreateWalletRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataCreateWallet(fermataCreateWalletRequest?: FermataCreateWalletRequest, options?: RawAxiosRequestConfig): AxiosPromise<FermataCreateWallet200Response> {
            return localVarFp.fermataCreateWallet(fermataCreateWalletRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Freeze a wallet, blocking all transactions. Admin only.
         * @summary Freeze wallet
         * @param {FermataFreezeWalletRequest} [fermataFreezeWalletRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataFreezeWallet(fermataFreezeWalletRequest?: FermataFreezeWalletRequest, options?: RawAxiosRequestConfig): AxiosPromise<FermataCreateWallet200Response> {
            return localVarFp.fermataFreezeWallet(fermataFreezeWalletRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Get a single dealer by ID, including configuration and linked accounts.
         * @summary Get dealer
         * @param {string} dealerAccountId Dealer account ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataGetDealer(dealerAccountId: string, options?: RawAxiosRequestConfig): AxiosPromise<FermataCreateDealer200Response> {
            return localVarFp.fermataGetDealer(dealerAccountId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get a single wallet by ID, including balances and status.
         * @summary Get wallet
         * @param {string} walletId Wallet ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataGetWallet(walletId: string, options?: RawAxiosRequestConfig): AxiosPromise<FermataCreateWallet200Response> {
            return localVarFp.fermataGetWallet(walletId, options).then((request) => request(axios, basePath));
        },
        /**
         * Link an existing exchange trading account to the dealer as a liquidity provider for hedging.
         * @summary Link exchange account to dealer
         * @param {FermataLinkDealerRequest} [fermataLinkDealerRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataLinkDealer(fermataLinkDealerRequest?: FermataLinkDealerRequest, options?: RawAxiosRequestConfig): AxiosPromise<DeleteMarketInstrument200Response> {
            return localVarFp.fermataLinkDealer(fermataLinkDealerRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * List dealers with optional status filter. Admin only.
         * @summary List dealers
         * @param {DealerStatus} [status] Filter by dealer status
         * @param {number} [limit] Limit the number of returned results
         * @param {number} [offset] Offset of the returned results
         * @param {string} [cursor] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataListDealers(status?: DealerStatus, limit?: number, offset?: number, cursor?: string, options?: RawAxiosRequestConfig): AxiosPromise<FermataListDealers200Response> {
            return localVarFp.fermataListDealers(status, limit, offset, cursor, options).then((request) => request(axios, basePath));
        },
        /**
         * List wallets by type, owner, or dealer.
         * @summary List wallets
         * @param {WalletType} [walletType] Filter by wallet type
         * @param {number} [limit] Limit the number of returned results
         * @param {number} [offset] Offset of the returned results
         * @param {string} [cursor] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataListWallets(walletType?: WalletType, limit?: number, offset?: number, cursor?: string, options?: RawAxiosRequestConfig): AxiosPromise<FermataListWallets200Response> {
            return localVarFp.fermataListWallets(walletType, limit, offset, cursor, options).then((request) => request(axios, basePath));
        },
        /**
         * Pause a dealer — stops quoting but continues hedging open positions. Admin only.
         * @summary Pause dealer
         * @param {FermataPauseDealerRequest} [fermataPauseDealerRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataPauseDealer(fermataPauseDealerRequest?: FermataPauseDealerRequest, options?: RawAxiosRequestConfig): AxiosPromise<FermataCreateDealer200Response> {
            return localVarFp.fermataPauseDealer(fermataPauseDealerRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Resume a paused dealer — restores quoting capability. Admin only.
         * @summary Resume dealer
         * @param {FermataResumeDealerRequest} [fermataResumeDealerRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataResumeDealer(fermataResumeDealerRequest?: FermataResumeDealerRequest, options?: RawAxiosRequestConfig): AxiosPromise<FermataCreateDealer200Response> {
            return localVarFp.fermataResumeDealer(fermataResumeDealerRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Transfer assets between wallets owned by the same user under the same dealer.
         * @summary Transfer between wallets
         * @param {FermataTransferWalletRequest} [fermataTransferWalletRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataTransferWallet(fermataTransferWalletRequest?: FermataTransferWalletRequest, options?: RawAxiosRequestConfig): AxiosPromise<DeleteMarketInstrument200Response> {
            return localVarFp.fermataTransferWallet(fermataTransferWalletRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Unfreeze a previously frozen wallet, restoring transaction capabilities. Admin only.
         * @summary Unfreeze wallet
         * @param {FermataUnfreezeWalletRequest} [fermataUnfreezeWalletRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataUnfreezeWallet(fermataUnfreezeWalletRequest?: FermataUnfreezeWalletRequest, options?: RawAxiosRequestConfig): AxiosPromise<FermataCreateWallet200Response> {
            return localVarFp.fermataUnfreezeWallet(fermataUnfreezeWalletRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Unlink an exchange trading account from the dealer.
         * @summary Unlink exchange account from dealer
         * @param {FermataUnlinkDealerRequest} [fermataUnlinkDealerRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fermataUnlinkDealer(fermataUnlinkDealerRequest?: FermataUnlinkDealerRequest, options?: RawAxiosRequestConfig): AxiosPromise<DeleteMarketInstrument200Response> {
            return localVarFp.fermataUnlinkDealer(fermataUnlinkDealerRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FermataApi - object-oriented interface
 */
export class FermataApi extends BaseAPI {
    /**
     * Archive a dealer — permanently stops all operations. All open positions must be closed before archiving. Admin only.
     * @summary Archive dealer
     * @param {FermataArchiveDealerRequest} [fermataArchiveDealerRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public fermataArchiveDealer(fermataArchiveDealerRequest?: FermataArchiveDealerRequest, options?: RawAxiosRequestConfig) {
        return FermataApiFp(this.configuration).fermataArchiveDealer(fermataArchiveDealerRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Close a wallet. Terminal state — only a final withdrawal to zero balance is allowed after closing.
     * @summary Close wallet
     * @param {FermataCloseWalletRequest} [fermataCloseWalletRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public fermataCloseWallet(fermataCloseWalletRequest?: FermataCloseWalletRequest, options?: RawAxiosRequestConfig) {
        return FermataApiFp(this.configuration).fermataCloseWallet(fermataCloseWalletRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a new dealer account in the Fermata venue. Admin only. Provisions a Trading Account (venue=FERMATA), a dealer wallet in the Formance Ledger, and dealer configuration.
     * @summary Create dealer
     * @param {FermataCreateDealerRequest} [fermataCreateDealerRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public fermataCreateDealer(fermataCreateDealerRequest?: FermataCreateDealerRequest, options?: RawAxiosRequestConfig) {
        return FermataApiFp(this.configuration).fermataCreateDealer(fermataCreateDealerRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a new wallet in the Fermata ledger.
     * @summary Create wallet
     * @param {FermataCreateWalletRequest} [fermataCreateWalletRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public fermataCreateWallet(fermataCreateWalletRequest?: FermataCreateWalletRequest, options?: RawAxiosRequestConfig) {
        return FermataApiFp(this.configuration).fermataCreateWallet(fermataCreateWalletRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Freeze a wallet, blocking all transactions. Admin only.
     * @summary Freeze wallet
     * @param {FermataFreezeWalletRequest} [fermataFreezeWalletRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public fermataFreezeWallet(fermataFreezeWalletRequest?: FermataFreezeWalletRequest, options?: RawAxiosRequestConfig) {
        return FermataApiFp(this.configuration).fermataFreezeWallet(fermataFreezeWalletRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get a single dealer by ID, including configuration and linked accounts.
     * @summary Get dealer
     * @param {string} dealerAccountId Dealer account ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public fermataGetDealer(dealerAccountId: string, options?: RawAxiosRequestConfig) {
        return FermataApiFp(this.configuration).fermataGetDealer(dealerAccountId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get a single wallet by ID, including balances and status.
     * @summary Get wallet
     * @param {string} walletId Wallet ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public fermataGetWallet(walletId: string, options?: RawAxiosRequestConfig) {
        return FermataApiFp(this.configuration).fermataGetWallet(walletId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Link an existing exchange trading account to the dealer as a liquidity provider for hedging.
     * @summary Link exchange account to dealer
     * @param {FermataLinkDealerRequest} [fermataLinkDealerRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public fermataLinkDealer(fermataLinkDealerRequest?: FermataLinkDealerRequest, options?: RawAxiosRequestConfig) {
        return FermataApiFp(this.configuration).fermataLinkDealer(fermataLinkDealerRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List dealers with optional status filter. Admin only.
     * @summary List dealers
     * @param {DealerStatus} [status] Filter by dealer status
     * @param {number} [limit] Limit the number of returned results
     * @param {number} [offset] Offset of the returned results
     * @param {string} [cursor] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public fermataListDealers(status?: DealerStatus, limit?: number, offset?: number, cursor?: string, options?: RawAxiosRequestConfig) {
        return FermataApiFp(this.configuration).fermataListDealers(status, limit, offset, cursor, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List wallets by type, owner, or dealer.
     * @summary List wallets
     * @param {WalletType} [walletType] Filter by wallet type
     * @param {number} [limit] Limit the number of returned results
     * @param {number} [offset] Offset of the returned results
     * @param {string} [cursor] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public fermataListWallets(walletType?: WalletType, limit?: number, offset?: number, cursor?: string, options?: RawAxiosRequestConfig) {
        return FermataApiFp(this.configuration).fermataListWallets(walletType, limit, offset, cursor, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Pause a dealer — stops quoting but continues hedging open positions. Admin only.
     * @summary Pause dealer
     * @param {FermataPauseDealerRequest} [fermataPauseDealerRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public fermataPauseDealer(fermataPauseDealerRequest?: FermataPauseDealerRequest, options?: RawAxiosRequestConfig) {
        return FermataApiFp(this.configuration).fermataPauseDealer(fermataPauseDealerRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Resume a paused dealer — restores quoting capability. Admin only.
     * @summary Resume dealer
     * @param {FermataResumeDealerRequest} [fermataResumeDealerRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public fermataResumeDealer(fermataResumeDealerRequest?: FermataResumeDealerRequest, options?: RawAxiosRequestConfig) {
        return FermataApiFp(this.configuration).fermataResumeDealer(fermataResumeDealerRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Transfer assets between wallets owned by the same user under the same dealer.
     * @summary Transfer between wallets
     * @param {FermataTransferWalletRequest} [fermataTransferWalletRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public fermataTransferWallet(fermataTransferWalletRequest?: FermataTransferWalletRequest, options?: RawAxiosRequestConfig) {
        return FermataApiFp(this.configuration).fermataTransferWallet(fermataTransferWalletRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Unfreeze a previously frozen wallet, restoring transaction capabilities. Admin only.
     * @summary Unfreeze wallet
     * @param {FermataUnfreezeWalletRequest} [fermataUnfreezeWalletRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public fermataUnfreezeWallet(fermataUnfreezeWalletRequest?: FermataUnfreezeWalletRequest, options?: RawAxiosRequestConfig) {
        return FermataApiFp(this.configuration).fermataUnfreezeWallet(fermataUnfreezeWalletRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Unlink an exchange trading account from the dealer.
     * @summary Unlink exchange account from dealer
     * @param {FermataUnlinkDealerRequest} [fermataUnlinkDealerRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public fermataUnlinkDealer(fermataUnlinkDealerRequest?: FermataUnlinkDealerRequest, options?: RawAxiosRequestConfig) {
        return FermataApiFp(this.configuration).fermataUnlinkDealer(fermataUnlinkDealerRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

