/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ListTradingAccountSubscriptions200Response } from '../models';
// @ts-ignore
import type { Root400Response } from '../models';
// @ts-ignore
import type { Root401Response } from '../models';
// @ts-ignore
import type { Root403Response } from '../models';
// @ts-ignore
import type { Root404Response } from '../models';
// @ts-ignore
import type { Root500Response } from '../models';
// @ts-ignore
import type { SubscribeMarketOrderBookRequest } from '../models';
// @ts-ignore
import type { SubscribeTradingAccount200Response } from '../models';
// @ts-ignore
import type { UnsubscribeRequest } from '../models';
/**
 * MarketSubscriptionApi - axios parameter creator
 */
export const MarketSubscriptionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * List active order book subscriptions
         * @summary List order book subscriptions
         * @param {string} [instrumentId] Instrument ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMarketOrderBookSubscriptions: async (instrumentId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/market/subscription/orderBook/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (instrumentId !== undefined) {
                localVarQueryParameter['instrumentId'] = instrumentId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Subscribe to real-time order book updates
         * @summary Subscribe to order book updates
         * @param {SubscribeMarketOrderBookRequest} [subscribeMarketOrderBookRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subscribeMarketOrderBook: async (subscribeMarketOrderBookRequest?: SubscribeMarketOrderBookRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/market/subscription/orderBook/subscribe`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(subscribeMarketOrderBookRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Unsubscribe from real-time order book updates
         * @summary Unsubscribe from order book updates
         * @param {UnsubscribeRequest} [unsubscribeRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unsubscribeMarketOrderBook: async (unsubscribeRequest?: UnsubscribeRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/market/subscription/orderBook/unsubscribe`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(unsubscribeRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MarketSubscriptionApi - functional programming interface
 */
export const MarketSubscriptionApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MarketSubscriptionApiAxiosParamCreator(configuration)
    return {
        /**
         * List active order book subscriptions
         * @summary List order book subscriptions
         * @param {string} [instrumentId] Instrument ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listMarketOrderBookSubscriptions(instrumentId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListTradingAccountSubscriptions200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listMarketOrderBookSubscriptions(instrumentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MarketSubscriptionApi.listMarketOrderBookSubscriptions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Subscribe to real-time order book updates
         * @summary Subscribe to order book updates
         * @param {SubscribeMarketOrderBookRequest} [subscribeMarketOrderBookRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async subscribeMarketOrderBook(subscribeMarketOrderBookRequest?: SubscribeMarketOrderBookRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubscribeTradingAccount200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.subscribeMarketOrderBook(subscribeMarketOrderBookRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MarketSubscriptionApi.subscribeMarketOrderBook']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Unsubscribe from real-time order book updates
         * @summary Unsubscribe from order book updates
         * @param {UnsubscribeRequest} [unsubscribeRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async unsubscribeMarketOrderBook(unsubscribeRequest?: UnsubscribeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubscribeTradingAccount200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.unsubscribeMarketOrderBook(unsubscribeRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MarketSubscriptionApi.unsubscribeMarketOrderBook']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MarketSubscriptionApi - factory interface
 */
export const MarketSubscriptionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MarketSubscriptionApiFp(configuration)
    return {
        /**
         * List active order book subscriptions
         * @summary List order book subscriptions
         * @param {string} [instrumentId] Instrument ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMarketOrderBookSubscriptions(instrumentId?: string, options?: RawAxiosRequestConfig): AxiosPromise<ListTradingAccountSubscriptions200Response> {
            return localVarFp.listMarketOrderBookSubscriptions(instrumentId, options).then((request) => request(axios, basePath));
        },
        /**
         * Subscribe to real-time order book updates
         * @summary Subscribe to order book updates
         * @param {SubscribeMarketOrderBookRequest} [subscribeMarketOrderBookRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subscribeMarketOrderBook(subscribeMarketOrderBookRequest?: SubscribeMarketOrderBookRequest, options?: RawAxiosRequestConfig): AxiosPromise<SubscribeTradingAccount200Response> {
            return localVarFp.subscribeMarketOrderBook(subscribeMarketOrderBookRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Unsubscribe from real-time order book updates
         * @summary Unsubscribe from order book updates
         * @param {UnsubscribeRequest} [unsubscribeRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unsubscribeMarketOrderBook(unsubscribeRequest?: UnsubscribeRequest, options?: RawAxiosRequestConfig): AxiosPromise<SubscribeTradingAccount200Response> {
            return localVarFp.unsubscribeMarketOrderBook(unsubscribeRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MarketSubscriptionApi - object-oriented interface
 */
export class MarketSubscriptionApi extends BaseAPI {
    /**
     * List active order book subscriptions
     * @summary List order book subscriptions
     * @param {string} [instrumentId] Instrument ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listMarketOrderBookSubscriptions(instrumentId?: string, options?: RawAxiosRequestConfig) {
        return MarketSubscriptionApiFp(this.configuration).listMarketOrderBookSubscriptions(instrumentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Subscribe to real-time order book updates
     * @summary Subscribe to order book updates
     * @param {SubscribeMarketOrderBookRequest} [subscribeMarketOrderBookRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public subscribeMarketOrderBook(subscribeMarketOrderBookRequest?: SubscribeMarketOrderBookRequest, options?: RawAxiosRequestConfig) {
        return MarketSubscriptionApiFp(this.configuration).subscribeMarketOrderBook(subscribeMarketOrderBookRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Unsubscribe from real-time order book updates
     * @summary Unsubscribe from order book updates
     * @param {UnsubscribeRequest} [unsubscribeRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public unsubscribeMarketOrderBook(unsubscribeRequest?: UnsubscribeRequest, options?: RawAxiosRequestConfig) {
        return MarketSubscriptionApiFp(this.configuration).unsubscribeMarketOrderBook(unsubscribeRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

