/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ListTradingAccountPortfolios200Response } from '../models';
// @ts-ignore
import type { Root400Response } from '../models';
// @ts-ignore
import type { Root401Response } from '../models';
// @ts-ignore
import type { Root403Response } from '../models';
// @ts-ignore
import type { Root404Response } from '../models';
// @ts-ignore
import type { Root500Response } from '../models';
// @ts-ignore
import type { Venue } from '../models';
/**
 * TradingAccountPortfolioApi - axios parameter creator
 */
export const TradingAccountPortfolioApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * List portfolios across all trading accounts
         * @summary List trading account portfolios
         * @param {string} [tradingAccountId] Trading account ID
         * @param {Venue} [venue] Exchange type
         * @param {string} [currency] Currency
         * @param {number} [limit] Limit the number of returned results
         * @param {number} [offset] Offset of the returned results
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTradingAccountPortfolios: async (tradingAccountId?: string, venue?: Venue, currency?: string, limit?: number, offset?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/tradingAccount/portfolio/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (tradingAccountId !== undefined) {
                localVarQueryParameter['tradingAccountId'] = tradingAccountId;
            }

            if (venue !== undefined) {
                localVarQueryParameter['venue'] = venue;
            }

            if (currency !== undefined) {
                localVarQueryParameter['currency'] = currency;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TradingAccountPortfolioApi - functional programming interface
 */
export const TradingAccountPortfolioApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TradingAccountPortfolioApiAxiosParamCreator(configuration)
    return {
        /**
         * List portfolios across all trading accounts
         * @summary List trading account portfolios
         * @param {string} [tradingAccountId] Trading account ID
         * @param {Venue} [venue] Exchange type
         * @param {string} [currency] Currency
         * @param {number} [limit] Limit the number of returned results
         * @param {number} [offset] Offset of the returned results
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTradingAccountPortfolios(tradingAccountId?: string, venue?: Venue, currency?: string, limit?: number, offset?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListTradingAccountPortfolios200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listTradingAccountPortfolios(tradingAccountId, venue, currency, limit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TradingAccountPortfolioApi.listTradingAccountPortfolios']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TradingAccountPortfolioApi - factory interface
 */
export const TradingAccountPortfolioApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TradingAccountPortfolioApiFp(configuration)
    return {
        /**
         * List portfolios across all trading accounts
         * @summary List trading account portfolios
         * @param {string} [tradingAccountId] Trading account ID
         * @param {Venue} [venue] Exchange type
         * @param {string} [currency] Currency
         * @param {number} [limit] Limit the number of returned results
         * @param {number} [offset] Offset of the returned results
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTradingAccountPortfolios(tradingAccountId?: string, venue?: Venue, currency?: string, limit?: number, offset?: number, options?: RawAxiosRequestConfig): AxiosPromise<ListTradingAccountPortfolios200Response> {
            return localVarFp.listTradingAccountPortfolios(tradingAccountId, venue, currency, limit, offset, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TradingAccountPortfolioApi - object-oriented interface
 */
export class TradingAccountPortfolioApi extends BaseAPI {
    /**
     * List portfolios across all trading accounts
     * @summary List trading account portfolios
     * @param {string} [tradingAccountId] Trading account ID
     * @param {Venue} [venue] Exchange type
     * @param {string} [currency] Currency
     * @param {number} [limit] Limit the number of returned results
     * @param {number} [offset] Offset of the returned results
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listTradingAccountPortfolios(tradingAccountId?: string, venue?: Venue, currency?: string, limit?: number, offset?: number, options?: RawAxiosRequestConfig) {
        return TradingAccountPortfolioApiFp(this.configuration).listTradingAccountPortfolios(tradingAccountId, venue, currency, limit, offset, options).then((request) => request(this.axios, this.basePath));
    }
}

