/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ListTradingAccountSubscriptions200Response } from '../models';
// @ts-ignore
import type { Root400Response } from '../models';
// @ts-ignore
import type { Root401Response } from '../models';
// @ts-ignore
import type { Root403Response } from '../models';
// @ts-ignore
import type { Root404Response } from '../models';
// @ts-ignore
import type { Root500Response } from '../models';
// @ts-ignore
import type { SubscribeTradingAccount200Response } from '../models';
// @ts-ignore
import type { SubscribeTradingAccountRequest } from '../models';
// @ts-ignore
import type { UnsubscribeRequest } from '../models';
/**
 * TradingAccountSubscriptionApi - axios parameter creator
 */
export const TradingAccountSubscriptionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * List active trading account subscriptions
         * @summary List trading account subscriptions
         * @param {string} [tradingAccountId] Trading account ID
         * @param {number} [limit] Limit the number of returned results
         * @param {number} [offset] Offset of the returned results
         * @param {string} [cursor] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTradingAccountSubscriptions: async (tradingAccountId?: string, limit?: number, offset?: number, cursor?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/tradingAccount/subscription/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (tradingAccountId !== undefined) {
                localVarQueryParameter['tradingAccountId'] = tradingAccountId;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Subscribe to real-time trading account updates
         * @summary Subscribe to trading account updates
         * @param {SubscribeTradingAccountRequest} [subscribeTradingAccountRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subscribeTradingAccount: async (subscribeTradingAccountRequest?: SubscribeTradingAccountRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/tradingAccount/subscription/subscribe`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(subscribeTradingAccountRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Unsubscribe from real-time trading account updates
         * @summary Unsubscribe from trading account updates
         * @param {UnsubscribeRequest} [unsubscribeRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unsubscribeTradingAccount: async (unsubscribeRequest?: UnsubscribeRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/tradingAccount/subscription/unsubscribe`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(unsubscribeRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TradingAccountSubscriptionApi - functional programming interface
 */
export const TradingAccountSubscriptionApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TradingAccountSubscriptionApiAxiosParamCreator(configuration)
    return {
        /**
         * List active trading account subscriptions
         * @summary List trading account subscriptions
         * @param {string} [tradingAccountId] Trading account ID
         * @param {number} [limit] Limit the number of returned results
         * @param {number} [offset] Offset of the returned results
         * @param {string} [cursor] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTradingAccountSubscriptions(tradingAccountId?: string, limit?: number, offset?: number, cursor?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListTradingAccountSubscriptions200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listTradingAccountSubscriptions(tradingAccountId, limit, offset, cursor, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TradingAccountSubscriptionApi.listTradingAccountSubscriptions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Subscribe to real-time trading account updates
         * @summary Subscribe to trading account updates
         * @param {SubscribeTradingAccountRequest} [subscribeTradingAccountRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async subscribeTradingAccount(subscribeTradingAccountRequest?: SubscribeTradingAccountRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubscribeTradingAccount200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.subscribeTradingAccount(subscribeTradingAccountRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TradingAccountSubscriptionApi.subscribeTradingAccount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Unsubscribe from real-time trading account updates
         * @summary Unsubscribe from trading account updates
         * @param {UnsubscribeRequest} [unsubscribeRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async unsubscribeTradingAccount(unsubscribeRequest?: UnsubscribeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubscribeTradingAccount200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.unsubscribeTradingAccount(unsubscribeRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TradingAccountSubscriptionApi.unsubscribeTradingAccount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TradingAccountSubscriptionApi - factory interface
 */
export const TradingAccountSubscriptionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TradingAccountSubscriptionApiFp(configuration)
    return {
        /**
         * List active trading account subscriptions
         * @summary List trading account subscriptions
         * @param {string} [tradingAccountId] Trading account ID
         * @param {number} [limit] Limit the number of returned results
         * @param {number} [offset] Offset of the returned results
         * @param {string} [cursor] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTradingAccountSubscriptions(tradingAccountId?: string, limit?: number, offset?: number, cursor?: string, options?: RawAxiosRequestConfig): AxiosPromise<ListTradingAccountSubscriptions200Response> {
            return localVarFp.listTradingAccountSubscriptions(tradingAccountId, limit, offset, cursor, options).then((request) => request(axios, basePath));
        },
        /**
         * Subscribe to real-time trading account updates
         * @summary Subscribe to trading account updates
         * @param {SubscribeTradingAccountRequest} [subscribeTradingAccountRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        subscribeTradingAccount(subscribeTradingAccountRequest?: SubscribeTradingAccountRequest, options?: RawAxiosRequestConfig): AxiosPromise<SubscribeTradingAccount200Response> {
            return localVarFp.subscribeTradingAccount(subscribeTradingAccountRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Unsubscribe from real-time trading account updates
         * @summary Unsubscribe from trading account updates
         * @param {UnsubscribeRequest} [unsubscribeRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unsubscribeTradingAccount(unsubscribeRequest?: UnsubscribeRequest, options?: RawAxiosRequestConfig): AxiosPromise<SubscribeTradingAccount200Response> {
            return localVarFp.unsubscribeTradingAccount(unsubscribeRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TradingAccountSubscriptionApi - object-oriented interface
 */
export class TradingAccountSubscriptionApi extends BaseAPI {
    /**
     * List active trading account subscriptions
     * @summary List trading account subscriptions
     * @param {string} [tradingAccountId] Trading account ID
     * @param {number} [limit] Limit the number of returned results
     * @param {number} [offset] Offset of the returned results
     * @param {string} [cursor] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listTradingAccountSubscriptions(tradingAccountId?: string, limit?: number, offset?: number, cursor?: string, options?: RawAxiosRequestConfig) {
        return TradingAccountSubscriptionApiFp(this.configuration).listTradingAccountSubscriptions(tradingAccountId, limit, offset, cursor, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Subscribe to real-time trading account updates
     * @summary Subscribe to trading account updates
     * @param {SubscribeTradingAccountRequest} [subscribeTradingAccountRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public subscribeTradingAccount(subscribeTradingAccountRequest?: SubscribeTradingAccountRequest, options?: RawAxiosRequestConfig) {
        return TradingAccountSubscriptionApiFp(this.configuration).subscribeTradingAccount(subscribeTradingAccountRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Unsubscribe from real-time trading account updates
     * @summary Unsubscribe from trading account updates
     * @param {UnsubscribeRequest} [unsubscribeRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public unsubscribeTradingAccount(unsubscribeRequest?: UnsubscribeRequest, options?: RawAxiosRequestConfig) {
        return TradingAccountSubscriptionApiFp(this.configuration).unsubscribeTradingAccount(unsubscribeRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

