/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ConnectTradingAccount200Response } from '../models';
// @ts-ignore
import type { ConnectTradingAccountRequest } from '../models';
// @ts-ignore
import type { DisableTradingAccountRequest } from '../models';
// @ts-ignore
import type { DisconnectTradingAccountRequest } from '../models';
// @ts-ignore
import type { EnableTradingAccountRequest } from '../models';
// @ts-ignore
import type { ListTradingAccountOperations200Response } from '../models';
// @ts-ignore
import type { ListTradingAccounts200Response } from '../models';
// @ts-ignore
import type { OperationType } from '../models';
// @ts-ignore
import type { Root400Response } from '../models';
// @ts-ignore
import type { Root401Response } from '../models';
// @ts-ignore
import type { Root403Response } from '../models';
// @ts-ignore
import type { Root404Response } from '../models';
// @ts-ignore
import type { Root500Response } from '../models';
// @ts-ignore
import type { TradingAccountStatus } from '../models';
// @ts-ignore
import type { UpdateTradingAccountRequest } from '../models';
// @ts-ignore
import type { Venue } from '../models';
/**
 * TradingAccountApi - axios parameter creator
 */
export const TradingAccountApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Connect to a trading account
         * @summary Connect trading account
         * @param {ConnectTradingAccountRequest} [connectTradingAccountRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        connectTradingAccount: async (connectTradingAccountRequest?: ConnectTradingAccountRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/tradingAccount/connect`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(connectTradingAccountRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Disable a trading account, the trading account will be disabled and no longer available for trading.
         * @summary Disable trading account
         * @param {DisableTradingAccountRequest} [disableTradingAccountRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        disableTradingAccount: async (disableTradingAccountRequest?: DisableTradingAccountRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/tradingAccount/disable`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(disableTradingAccountRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Disconnect from a trading account, all trading functions and the event stream notification will be stopped. The trading account will be archived and no longer available for trading. If the same trading account need to be connected again, please use the connect trading account API to create another new trading account.
         * @summary Disconnect trading account
         * @param {DisconnectTradingAccountRequest} [disconnectTradingAccountRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        disconnectTradingAccount: async (disconnectTradingAccountRequest?: DisconnectTradingAccountRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/tradingAccount/disconnect`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(disconnectTradingAccountRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Enable a trading account, the trading account will be enabled and available for trading.
         * @summary Enable trading account
         * @param {EnableTradingAccountRequest} [enableTradingAccountRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        enableTradingAccount: async (enableTradingAccountRequest?: EnableTradingAccountRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/tradingAccount/enable`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(enableTradingAccountRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List operations history for trading accounts
         * @summary List trading account operations
         * @param {string} [tradingAccountId] Trading account ID
         * @param {OperationType} [operationType] Operation type
         * @param {number} [startTime] Start time (in unix milliseconds), of the created at field
         * @param {number} [endTime] End time (in unix milliseconds), of the created at field
         * @param {number} [limit] Limit the number of returned results
         * @param {number} [offset] Offset of the returned results
         * @param {string} [cursor] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTradingAccountOperations: async (tradingAccountId?: string, operationType?: OperationType, startTime?: number, endTime?: number, limit?: number, offset?: number, cursor?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/tradingAccount/operation/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (tradingAccountId !== undefined) {
                localVarQueryParameter['tradingAccountId'] = tradingAccountId;
            }

            if (operationType !== undefined) {
                localVarQueryParameter['operationType'] = operationType;
            }

            if (startTime !== undefined) {
                localVarQueryParameter['startTime'] = startTime;
            }

            if (endTime !== undefined) {
                localVarQueryParameter['endTime'] = endTime;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List all trading accounts
         * @summary List trading accounts
         * @param {string} [tradingAccountId] Trading account ID
         * @param {Venue} [venue] Exchange type
         * @param {TradingAccountStatus} [accountStatus] Account status
         * @param {number} [limit] Limit the number of returned results
         * @param {number} [offset] Offset of the returned results
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTradingAccounts: async (tradingAccountId?: string, venue?: Venue, accountStatus?: TradingAccountStatus, limit?: number, offset?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/tradingAccount/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (tradingAccountId !== undefined) {
                localVarQueryParameter['tradingAccountId'] = tradingAccountId;
            }

            if (venue !== undefined) {
                localVarQueryParameter['venue'] = venue;
            }

            if (accountStatus !== undefined) {
                localVarQueryParameter['accountStatus'] = accountStatus;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update trading account information
         * @summary Update trading account
         * @param {UpdateTradingAccountRequest} [updateTradingAccountRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTradingAccount: async (updateTradingAccountRequest?: UpdateTradingAccountRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/tradingAccount/update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateTradingAccountRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TradingAccountApi - functional programming interface
 */
export const TradingAccountApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TradingAccountApiAxiosParamCreator(configuration)
    return {
        /**
         * Connect to a trading account
         * @summary Connect trading account
         * @param {ConnectTradingAccountRequest} [connectTradingAccountRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async connectTradingAccount(connectTradingAccountRequest?: ConnectTradingAccountRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConnectTradingAccount200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.connectTradingAccount(connectTradingAccountRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TradingAccountApi.connectTradingAccount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Disable a trading account, the trading account will be disabled and no longer available for trading.
         * @summary Disable trading account
         * @param {DisableTradingAccountRequest} [disableTradingAccountRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async disableTradingAccount(disableTradingAccountRequest?: DisableTradingAccountRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConnectTradingAccount200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.disableTradingAccount(disableTradingAccountRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TradingAccountApi.disableTradingAccount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Disconnect from a trading account, all trading functions and the event stream notification will be stopped. The trading account will be archived and no longer available for trading. If the same trading account need to be connected again, please use the connect trading account API to create another new trading account.
         * @summary Disconnect trading account
         * @param {DisconnectTradingAccountRequest} [disconnectTradingAccountRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async disconnectTradingAccount(disconnectTradingAccountRequest?: DisconnectTradingAccountRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConnectTradingAccount200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.disconnectTradingAccount(disconnectTradingAccountRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TradingAccountApi.disconnectTradingAccount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Enable a trading account, the trading account will be enabled and available for trading.
         * @summary Enable trading account
         * @param {EnableTradingAccountRequest} [enableTradingAccountRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async enableTradingAccount(enableTradingAccountRequest?: EnableTradingAccountRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConnectTradingAccount200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.enableTradingAccount(enableTradingAccountRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TradingAccountApi.enableTradingAccount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List operations history for trading accounts
         * @summary List trading account operations
         * @param {string} [tradingAccountId] Trading account ID
         * @param {OperationType} [operationType] Operation type
         * @param {number} [startTime] Start time (in unix milliseconds), of the created at field
         * @param {number} [endTime] End time (in unix milliseconds), of the created at field
         * @param {number} [limit] Limit the number of returned results
         * @param {number} [offset] Offset of the returned results
         * @param {string} [cursor] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTradingAccountOperations(tradingAccountId?: string, operationType?: OperationType, startTime?: number, endTime?: number, limit?: number, offset?: number, cursor?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListTradingAccountOperations200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listTradingAccountOperations(tradingAccountId, operationType, startTime, endTime, limit, offset, cursor, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TradingAccountApi.listTradingAccountOperations']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List all trading accounts
         * @summary List trading accounts
         * @param {string} [tradingAccountId] Trading account ID
         * @param {Venue} [venue] Exchange type
         * @param {TradingAccountStatus} [accountStatus] Account status
         * @param {number} [limit] Limit the number of returned results
         * @param {number} [offset] Offset of the returned results
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTradingAccounts(tradingAccountId?: string, venue?: Venue, accountStatus?: TradingAccountStatus, limit?: number, offset?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListTradingAccounts200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listTradingAccounts(tradingAccountId, venue, accountStatus, limit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TradingAccountApi.listTradingAccounts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update trading account information
         * @summary Update trading account
         * @param {UpdateTradingAccountRequest} [updateTradingAccountRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateTradingAccount(updateTradingAccountRequest?: UpdateTradingAccountRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConnectTradingAccount200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateTradingAccount(updateTradingAccountRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TradingAccountApi.updateTradingAccount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TradingAccountApi - factory interface
 */
export const TradingAccountApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TradingAccountApiFp(configuration)
    return {
        /**
         * Connect to a trading account
         * @summary Connect trading account
         * @param {ConnectTradingAccountRequest} [connectTradingAccountRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        connectTradingAccount(connectTradingAccountRequest?: ConnectTradingAccountRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConnectTradingAccount200Response> {
            return localVarFp.connectTradingAccount(connectTradingAccountRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Disable a trading account, the trading account will be disabled and no longer available for trading.
         * @summary Disable trading account
         * @param {DisableTradingAccountRequest} [disableTradingAccountRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        disableTradingAccount(disableTradingAccountRequest?: DisableTradingAccountRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConnectTradingAccount200Response> {
            return localVarFp.disableTradingAccount(disableTradingAccountRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Disconnect from a trading account, all trading functions and the event stream notification will be stopped. The trading account will be archived and no longer available for trading. If the same trading account need to be connected again, please use the connect trading account API to create another new trading account.
         * @summary Disconnect trading account
         * @param {DisconnectTradingAccountRequest} [disconnectTradingAccountRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        disconnectTradingAccount(disconnectTradingAccountRequest?: DisconnectTradingAccountRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConnectTradingAccount200Response> {
            return localVarFp.disconnectTradingAccount(disconnectTradingAccountRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Enable a trading account, the trading account will be enabled and available for trading.
         * @summary Enable trading account
         * @param {EnableTradingAccountRequest} [enableTradingAccountRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        enableTradingAccount(enableTradingAccountRequest?: EnableTradingAccountRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConnectTradingAccount200Response> {
            return localVarFp.enableTradingAccount(enableTradingAccountRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * List operations history for trading accounts
         * @summary List trading account operations
         * @param {string} [tradingAccountId] Trading account ID
         * @param {OperationType} [operationType] Operation type
         * @param {number} [startTime] Start time (in unix milliseconds), of the created at field
         * @param {number} [endTime] End time (in unix milliseconds), of the created at field
         * @param {number} [limit] Limit the number of returned results
         * @param {number} [offset] Offset of the returned results
         * @param {string} [cursor] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTradingAccountOperations(tradingAccountId?: string, operationType?: OperationType, startTime?: number, endTime?: number, limit?: number, offset?: number, cursor?: string, options?: RawAxiosRequestConfig): AxiosPromise<ListTradingAccountOperations200Response> {
            return localVarFp.listTradingAccountOperations(tradingAccountId, operationType, startTime, endTime, limit, offset, cursor, options).then((request) => request(axios, basePath));
        },
        /**
         * List all trading accounts
         * @summary List trading accounts
         * @param {string} [tradingAccountId] Trading account ID
         * @param {Venue} [venue] Exchange type
         * @param {TradingAccountStatus} [accountStatus] Account status
         * @param {number} [limit] Limit the number of returned results
         * @param {number} [offset] Offset of the returned results
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTradingAccounts(tradingAccountId?: string, venue?: Venue, accountStatus?: TradingAccountStatus, limit?: number, offset?: number, options?: RawAxiosRequestConfig): AxiosPromise<ListTradingAccounts200Response> {
            return localVarFp.listTradingAccounts(tradingAccountId, venue, accountStatus, limit, offset, options).then((request) => request(axios, basePath));
        },
        /**
         * Update trading account information
         * @summary Update trading account
         * @param {UpdateTradingAccountRequest} [updateTradingAccountRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTradingAccount(updateTradingAccountRequest?: UpdateTradingAccountRequest, options?: RawAxiosRequestConfig): AxiosPromise<ConnectTradingAccount200Response> {
            return localVarFp.updateTradingAccount(updateTradingAccountRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TradingAccountApi - object-oriented interface
 */
export class TradingAccountApi extends BaseAPI {
    /**
     * Connect to a trading account
     * @summary Connect trading account
     * @param {ConnectTradingAccountRequest} [connectTradingAccountRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public connectTradingAccount(connectTradingAccountRequest?: ConnectTradingAccountRequest, options?: RawAxiosRequestConfig) {
        return TradingAccountApiFp(this.configuration).connectTradingAccount(connectTradingAccountRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Disable a trading account, the trading account will be disabled and no longer available for trading.
     * @summary Disable trading account
     * @param {DisableTradingAccountRequest} [disableTradingAccountRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public disableTradingAccount(disableTradingAccountRequest?: DisableTradingAccountRequest, options?: RawAxiosRequestConfig) {
        return TradingAccountApiFp(this.configuration).disableTradingAccount(disableTradingAccountRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Disconnect from a trading account, all trading functions and the event stream notification will be stopped. The trading account will be archived and no longer available for trading. If the same trading account need to be connected again, please use the connect trading account API to create another new trading account.
     * @summary Disconnect trading account
     * @param {DisconnectTradingAccountRequest} [disconnectTradingAccountRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public disconnectTradingAccount(disconnectTradingAccountRequest?: DisconnectTradingAccountRequest, options?: RawAxiosRequestConfig) {
        return TradingAccountApiFp(this.configuration).disconnectTradingAccount(disconnectTradingAccountRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Enable a trading account, the trading account will be enabled and available for trading.
     * @summary Enable trading account
     * @param {EnableTradingAccountRequest} [enableTradingAccountRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public enableTradingAccount(enableTradingAccountRequest?: EnableTradingAccountRequest, options?: RawAxiosRequestConfig) {
        return TradingAccountApiFp(this.configuration).enableTradingAccount(enableTradingAccountRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List operations history for trading accounts
     * @summary List trading account operations
     * @param {string} [tradingAccountId] Trading account ID
     * @param {OperationType} [operationType] Operation type
     * @param {number} [startTime] Start time (in unix milliseconds), of the created at field
     * @param {number} [endTime] End time (in unix milliseconds), of the created at field
     * @param {number} [limit] Limit the number of returned results
     * @param {number} [offset] Offset of the returned results
     * @param {string} [cursor] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listTradingAccountOperations(tradingAccountId?: string, operationType?: OperationType, startTime?: number, endTime?: number, limit?: number, offset?: number, cursor?: string, options?: RawAxiosRequestConfig) {
        return TradingAccountApiFp(this.configuration).listTradingAccountOperations(tradingAccountId, operationType, startTime, endTime, limit, offset, cursor, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List all trading accounts
     * @summary List trading accounts
     * @param {string} [tradingAccountId] Trading account ID
     * @param {Venue} [venue] Exchange type
     * @param {TradingAccountStatus} [accountStatus] Account status
     * @param {number} [limit] Limit the number of returned results
     * @param {number} [offset] Offset of the returned results
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listTradingAccounts(tradingAccountId?: string, venue?: Venue, accountStatus?: TradingAccountStatus, limit?: number, offset?: number, options?: RawAxiosRequestConfig) {
        return TradingAccountApiFp(this.configuration).listTradingAccounts(tradingAccountId, venue, accountStatus, limit, offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update trading account information
     * @summary Update trading account
     * @param {UpdateTradingAccountRequest} [updateTradingAccountRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateTradingAccount(updateTradingAccountRequest?: UpdateTradingAccountRequest, options?: RawAxiosRequestConfig) {
        return TradingAccountApiFp(this.configuration).updateTradingAccount(updateTradingAccountRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

