/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BaseResponse } from '../models';
// @ts-ignore
import type { CancelTradeOrder200Response } from '../models';
// @ts-ignore
import type { CancelTradeOrderRequest } from '../models';
// @ts-ignore
import type { ListTradeOrders200Response } from '../models';
// @ts-ignore
import type { OrderStatus } from '../models';
// @ts-ignore
import type { QuoteRfq200Response } from '../models';
// @ts-ignore
import type { QuoteRfqRequest } from '../models';
// @ts-ignore
import type { SubmitTradeOrder200Response } from '../models';
// @ts-ignore
import type { SubmitTradeOrderRequest } from '../models';
/**
 * TradingApi - axios parameter creator
 */
export const TradingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Cancel an existing trade order
         * @summary Cancel trade order
         * @param {CancelTradeOrderRequest} [cancelTradeOrderRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelTradeOrder: async (cancelTradeOrderRequest?: CancelTradeOrderRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/tradeOrder/cancel`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cancelTradeOrderRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List trade orders with filtering options
         * @summary List trade orders
         * @param {string} [tradeOrderId] Trade order ID
         * @param {string} [orderListId] Filter by internal order list ID (UUID) to retrieve child orders of an OCO/OTO/OTOCO parent
         * @param {string} [externalOrderListId] Filter by exchange-assigned order list ID to retrieve child orders of an OCO/OTO/OTOCO parent
         * @param {OrderStatus} [orderStatus] Order status
         * @param {string} [tradingAccountId] Trading account ID
         * @param {string} [instrumentId] Instrument ID
         * @param {number} [startTime] Start time (in unix milliseconds), of the created at field
         * @param {number} [endTime] End time (in unix milliseconds), of the created at field
         * @param {number} [limit] Limit the number of returned results
         * @param {number} [offset] Offset of the returned results
         * @param {string} [cursor] 
         * @param {boolean} [ascending] Return records in ascending order
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTradeOrders: async (tradeOrderId?: string, orderListId?: string, externalOrderListId?: string, orderStatus?: OrderStatus, tradingAccountId?: string, instrumentId?: string, startTime?: number, endTime?: number, limit?: number, offset?: number, cursor?: string, ascending?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/tradeOrder/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (tradeOrderId !== undefined) {
                localVarQueryParameter['tradeOrderId'] = tradeOrderId;
            }

            if (orderListId !== undefined) {
                localVarQueryParameter['orderListId'] = orderListId;
            }

            if (externalOrderListId !== undefined) {
                localVarQueryParameter['externalOrderListId'] = externalOrderListId;
            }

            if (orderStatus !== undefined) {
                localVarQueryParameter['orderStatus'] = orderStatus;
            }

            if (tradingAccountId !== undefined) {
                localVarQueryParameter['tradingAccountId'] = tradingAccountId;
            }

            if (instrumentId !== undefined) {
                localVarQueryParameter['instrumentId'] = instrumentId;
            }

            if (startTime !== undefined) {
                localVarQueryParameter['startTime'] = startTime;
            }

            if (endTime !== undefined) {
                localVarQueryParameter['endTime'] = endTime;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (ascending !== undefined) {
                localVarQueryParameter['ascending'] = ascending;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Request a firm quote from the RFQ dealer. The quote is a bilateral contract between the user and the dealer with a guaranteed execution price and validity period.
         * @summary Request for Quote
         * @param {QuoteRfqRequest} [quoteRfqRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteRfq: async (quoteRfqRequest?: QuoteRfqRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/quote/rfq`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(quoteRfqRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Submit a new trade order
         * @summary Submit trade order
         * @param {SubmitTradeOrderRequest} [submitTradeOrderRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitTradeOrder: async (submitTradeOrderRequest?: SubmitTradeOrderRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v3/tradeOrder/submit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication SupabaseOAuth2BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(submitTradeOrderRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TradingApi - functional programming interface
 */
export const TradingApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TradingApiAxiosParamCreator(configuration)
    return {
        /**
         * Cancel an existing trade order
         * @summary Cancel trade order
         * @param {CancelTradeOrderRequest} [cancelTradeOrderRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async cancelTradeOrder(cancelTradeOrderRequest?: CancelTradeOrderRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CancelTradeOrder200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cancelTradeOrder(cancelTradeOrderRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TradingApi.cancelTradeOrder']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List trade orders with filtering options
         * @summary List trade orders
         * @param {string} [tradeOrderId] Trade order ID
         * @param {string} [orderListId] Filter by internal order list ID (UUID) to retrieve child orders of an OCO/OTO/OTOCO parent
         * @param {string} [externalOrderListId] Filter by exchange-assigned order list ID to retrieve child orders of an OCO/OTO/OTOCO parent
         * @param {OrderStatus} [orderStatus] Order status
         * @param {string} [tradingAccountId] Trading account ID
         * @param {string} [instrumentId] Instrument ID
         * @param {number} [startTime] Start time (in unix milliseconds), of the created at field
         * @param {number} [endTime] End time (in unix milliseconds), of the created at field
         * @param {number} [limit] Limit the number of returned results
         * @param {number} [offset] Offset of the returned results
         * @param {string} [cursor] 
         * @param {boolean} [ascending] Return records in ascending order
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTradeOrders(tradeOrderId?: string, orderListId?: string, externalOrderListId?: string, orderStatus?: OrderStatus, tradingAccountId?: string, instrumentId?: string, startTime?: number, endTime?: number, limit?: number, offset?: number, cursor?: string, ascending?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListTradeOrders200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listTradeOrders(tradeOrderId, orderListId, externalOrderListId, orderStatus, tradingAccountId, instrumentId, startTime, endTime, limit, offset, cursor, ascending, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TradingApi.listTradeOrders']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Request a firm quote from the RFQ dealer. The quote is a bilateral contract between the user and the dealer with a guaranteed execution price and validity period.
         * @summary Request for Quote
         * @param {QuoteRfqRequest} [quoteRfqRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quoteRfq(quoteRfqRequest?: QuoteRfqRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuoteRfq200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quoteRfq(quoteRfqRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TradingApi.quoteRfq']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Submit a new trade order
         * @summary Submit trade order
         * @param {SubmitTradeOrderRequest} [submitTradeOrderRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async submitTradeOrder(submitTradeOrderRequest?: SubmitTradeOrderRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubmitTradeOrder200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.submitTradeOrder(submitTradeOrderRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TradingApi.submitTradeOrder']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TradingApi - factory interface
 */
export const TradingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TradingApiFp(configuration)
    return {
        /**
         * Cancel an existing trade order
         * @summary Cancel trade order
         * @param {CancelTradeOrderRequest} [cancelTradeOrderRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        cancelTradeOrder(cancelTradeOrderRequest?: CancelTradeOrderRequest, options?: RawAxiosRequestConfig): AxiosPromise<CancelTradeOrder200Response> {
            return localVarFp.cancelTradeOrder(cancelTradeOrderRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * List trade orders with filtering options
         * @summary List trade orders
         * @param {string} [tradeOrderId] Trade order ID
         * @param {string} [orderListId] Filter by internal order list ID (UUID) to retrieve child orders of an OCO/OTO/OTOCO parent
         * @param {string} [externalOrderListId] Filter by exchange-assigned order list ID to retrieve child orders of an OCO/OTO/OTOCO parent
         * @param {OrderStatus} [orderStatus] Order status
         * @param {string} [tradingAccountId] Trading account ID
         * @param {string} [instrumentId] Instrument ID
         * @param {number} [startTime] Start time (in unix milliseconds), of the created at field
         * @param {number} [endTime] End time (in unix milliseconds), of the created at field
         * @param {number} [limit] Limit the number of returned results
         * @param {number} [offset] Offset of the returned results
         * @param {string} [cursor] 
         * @param {boolean} [ascending] Return records in ascending order
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTradeOrders(tradeOrderId?: string, orderListId?: string, externalOrderListId?: string, orderStatus?: OrderStatus, tradingAccountId?: string, instrumentId?: string, startTime?: number, endTime?: number, limit?: number, offset?: number, cursor?: string, ascending?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<ListTradeOrders200Response> {
            return localVarFp.listTradeOrders(tradeOrderId, orderListId, externalOrderListId, orderStatus, tradingAccountId, instrumentId, startTime, endTime, limit, offset, cursor, ascending, options).then((request) => request(axios, basePath));
        },
        /**
         * Request a firm quote from the RFQ dealer. The quote is a bilateral contract between the user and the dealer with a guaranteed execution price and validity period.
         * @summary Request for Quote
         * @param {QuoteRfqRequest} [quoteRfqRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quoteRfq(quoteRfqRequest?: QuoteRfqRequest, options?: RawAxiosRequestConfig): AxiosPromise<QuoteRfq200Response> {
            return localVarFp.quoteRfq(quoteRfqRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Submit a new trade order
         * @summary Submit trade order
         * @param {SubmitTradeOrderRequest} [submitTradeOrderRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitTradeOrder(submitTradeOrderRequest?: SubmitTradeOrderRequest, options?: RawAxiosRequestConfig): AxiosPromise<SubmitTradeOrder200Response> {
            return localVarFp.submitTradeOrder(submitTradeOrderRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TradingApi - object-oriented interface
 */
export class TradingApi extends BaseAPI {
    /**
     * Cancel an existing trade order
     * @summary Cancel trade order
     * @param {CancelTradeOrderRequest} [cancelTradeOrderRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public cancelTradeOrder(cancelTradeOrderRequest?: CancelTradeOrderRequest, options?: RawAxiosRequestConfig) {
        return TradingApiFp(this.configuration).cancelTradeOrder(cancelTradeOrderRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List trade orders with filtering options
     * @summary List trade orders
     * @param {string} [tradeOrderId] Trade order ID
     * @param {string} [orderListId] Filter by internal order list ID (UUID) to retrieve child orders of an OCO/OTO/OTOCO parent
     * @param {string} [externalOrderListId] Filter by exchange-assigned order list ID to retrieve child orders of an OCO/OTO/OTOCO parent
     * @param {OrderStatus} [orderStatus] Order status
     * @param {string} [tradingAccountId] Trading account ID
     * @param {string} [instrumentId] Instrument ID
     * @param {number} [startTime] Start time (in unix milliseconds), of the created at field
     * @param {number} [endTime] End time (in unix milliseconds), of the created at field
     * @param {number} [limit] Limit the number of returned results
     * @param {number} [offset] Offset of the returned results
     * @param {string} [cursor] 
     * @param {boolean} [ascending] Return records in ascending order
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listTradeOrders(tradeOrderId?: string, orderListId?: string, externalOrderListId?: string, orderStatus?: OrderStatus, tradingAccountId?: string, instrumentId?: string, startTime?: number, endTime?: number, limit?: number, offset?: number, cursor?: string, ascending?: boolean, options?: RawAxiosRequestConfig) {
        return TradingApiFp(this.configuration).listTradeOrders(tradeOrderId, orderListId, externalOrderListId, orderStatus, tradingAccountId, instrumentId, startTime, endTime, limit, offset, cursor, ascending, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Request a firm quote from the RFQ dealer. The quote is a bilateral contract between the user and the dealer with a guaranteed execution price and validity period.
     * @summary Request for Quote
     * @param {QuoteRfqRequest} [quoteRfqRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public quoteRfq(quoteRfqRequest?: QuoteRfqRequest, options?: RawAxiosRequestConfig) {
        return TradingApiFp(this.configuration).quoteRfq(quoteRfqRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Submit a new trade order
     * @summary Submit trade order
     * @param {SubmitTradeOrderRequest} [submitTradeOrderRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public submitTradeOrder(submitTradeOrderRequest?: SubmitTradeOrderRequest, options?: RawAxiosRequestConfig) {
        return TradingApiFp(this.configuration).submitTradeOrder(submitTradeOrderRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

