/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { Root400Response } from '../models';
// @ts-ignore
import type { Root401Response } from '../models';
// @ts-ignore
import type { WsCommand } from '../models';
// @ts-ignore
import type { WsReply } from '../models';
/**
 * WebSocketApi - axios parameter creator
 */
export const WebSocketApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * **This endpoint documents the WebSocket API protocol, not a REST endpoint.**  Connect to the Cadenza WebSocket API using the Centrifugo protocol. Use the WebSocket servers listed above (`wss://cadenza-ws.algo724.com/connection/websocket` for production or `wss://cadenza-ws-uat.algo724.com/connection/websocket` for UAT).  ## Connection Flow  1. **Establish WebSocket connection** to the server URL 2. **Send connect command** with authentication token 3. **Receive connect result** with client ID and session info 4. **Subscribe to channels** for real-time updates 5. **Receive push messages** with data updates  ## Authentication  Include your JWT token in the connect command: ```json {   \"connect\": {     \"token\": \"your-jwt-token\",     \"name\": \"your-client-name\"   },   \"id\": 1 } ```  ## Available Channels  Subscribe to channels for real-time updates:  | Channel Pattern | Description | |-----------------|-------------| | `tradingAccount:{accountId}` | Trading account updates (orders, portfolio, balances) | | `market:orderBook:{instrumentId}` | Order book updates for an instrument | | `market:trade:{instrumentId}` | Trade updates for an instrument |  ## Message Format  All WebSocket messages follow the Centrifugo JSON protocol format. See the WebSocket schemas section for detailed message structures.  For complete protocol documentation, refer to: - [Centrifugo Client Protocol](https://centrifugal.dev/docs/transports/client_protocol) - [Protocol Definitions (Protobuf)](https://github.com/centrifugal/protocol/blob/master/definitions/client.proto)
         * @summary WebSocket Connection
         * @param {WsCommand} [wsCommand] WebSocket command (sent after WebSocket connection is established)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        websocketConnect: async (wsCommand?: WsCommand, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/connection/websocket`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(wsCommand, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WebSocketApi - functional programming interface
 */
export const WebSocketApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WebSocketApiAxiosParamCreator(configuration)
    return {
        /**
         * **This endpoint documents the WebSocket API protocol, not a REST endpoint.**  Connect to the Cadenza WebSocket API using the Centrifugo protocol. Use the WebSocket servers listed above (`wss://cadenza-ws.algo724.com/connection/websocket` for production or `wss://cadenza-ws-uat.algo724.com/connection/websocket` for UAT).  ## Connection Flow  1. **Establish WebSocket connection** to the server URL 2. **Send connect command** with authentication token 3. **Receive connect result** with client ID and session info 4. **Subscribe to channels** for real-time updates 5. **Receive push messages** with data updates  ## Authentication  Include your JWT token in the connect command: ```json {   \"connect\": {     \"token\": \"your-jwt-token\",     \"name\": \"your-client-name\"   },   \"id\": 1 } ```  ## Available Channels  Subscribe to channels for real-time updates:  | Channel Pattern | Description | |-----------------|-------------| | `tradingAccount:{accountId}` | Trading account updates (orders, portfolio, balances) | | `market:orderBook:{instrumentId}` | Order book updates for an instrument | | `market:trade:{instrumentId}` | Trade updates for an instrument |  ## Message Format  All WebSocket messages follow the Centrifugo JSON protocol format. See the WebSocket schemas section for detailed message structures.  For complete protocol documentation, refer to: - [Centrifugo Client Protocol](https://centrifugal.dev/docs/transports/client_protocol) - [Protocol Definitions (Protobuf)](https://github.com/centrifugal/protocol/blob/master/definitions/client.proto)
         * @summary WebSocket Connection
         * @param {WsCommand} [wsCommand] WebSocket command (sent after WebSocket connection is established)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async websocketConnect(wsCommand?: WsCommand, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.websocketConnect(wsCommand, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WebSocketApi.websocketConnect']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WebSocketApi - factory interface
 */
export const WebSocketApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WebSocketApiFp(configuration)
    return {
        /**
         * **This endpoint documents the WebSocket API protocol, not a REST endpoint.**  Connect to the Cadenza WebSocket API using the Centrifugo protocol. Use the WebSocket servers listed above (`wss://cadenza-ws.algo724.com/connection/websocket` for production or `wss://cadenza-ws-uat.algo724.com/connection/websocket` for UAT).  ## Connection Flow  1. **Establish WebSocket connection** to the server URL 2. **Send connect command** with authentication token 3. **Receive connect result** with client ID and session info 4. **Subscribe to channels** for real-time updates 5. **Receive push messages** with data updates  ## Authentication  Include your JWT token in the connect command: ```json {   \"connect\": {     \"token\": \"your-jwt-token\",     \"name\": \"your-client-name\"   },   \"id\": 1 } ```  ## Available Channels  Subscribe to channels for real-time updates:  | Channel Pattern | Description | |-----------------|-------------| | `tradingAccount:{accountId}` | Trading account updates (orders, portfolio, balances) | | `market:orderBook:{instrumentId}` | Order book updates for an instrument | | `market:trade:{instrumentId}` | Trade updates for an instrument |  ## Message Format  All WebSocket messages follow the Centrifugo JSON protocol format. See the WebSocket schemas section for detailed message structures.  For complete protocol documentation, refer to: - [Centrifugo Client Protocol](https://centrifugal.dev/docs/transports/client_protocol) - [Protocol Definitions (Protobuf)](https://github.com/centrifugal/protocol/blob/master/definitions/client.proto)
         * @summary WebSocket Connection
         * @param {WsCommand} [wsCommand] WebSocket command (sent after WebSocket connection is established)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        websocketConnect(wsCommand?: WsCommand, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.websocketConnect(wsCommand, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WebSocketApi - object-oriented interface
 */
export class WebSocketApi extends BaseAPI {
    /**
     * **This endpoint documents the WebSocket API protocol, not a REST endpoint.**  Connect to the Cadenza WebSocket API using the Centrifugo protocol. Use the WebSocket servers listed above (`wss://cadenza-ws.algo724.com/connection/websocket` for production or `wss://cadenza-ws-uat.algo724.com/connection/websocket` for UAT).  ## Connection Flow  1. **Establish WebSocket connection** to the server URL 2. **Send connect command** with authentication token 3. **Receive connect result** with client ID and session info 4. **Subscribe to channels** for real-time updates 5. **Receive push messages** with data updates  ## Authentication  Include your JWT token in the connect command: ```json {   \"connect\": {     \"token\": \"your-jwt-token\",     \"name\": \"your-client-name\"   },   \"id\": 1 } ```  ## Available Channels  Subscribe to channels for real-time updates:  | Channel Pattern | Description | |-----------------|-------------| | `tradingAccount:{accountId}` | Trading account updates (orders, portfolio, balances) | | `market:orderBook:{instrumentId}` | Order book updates for an instrument | | `market:trade:{instrumentId}` | Trade updates for an instrument |  ## Message Format  All WebSocket messages follow the Centrifugo JSON protocol format. See the WebSocket schemas section for detailed message structures.  For complete protocol documentation, refer to: - [Centrifugo Client Protocol](https://centrifugal.dev/docs/transports/client_protocol) - [Protocol Definitions (Protobuf)](https://github.com/centrifugal/protocol/blob/master/definitions/client.proto)
     * @summary WebSocket Connection
     * @param {WsCommand} [wsCommand] WebSocket command (sent after WebSocket connection is established)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public websocketConnect(wsCommand?: WsCommand, options?: RawAxiosRequestConfig) {
        return WebSocketApiFp(this.configuration).websocketConnect(wsCommand, options).then((request) => request(this.axios, this.basePath));
    }
}

