/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OperationStatus } from './operation-status';
// May contain unused imports in some cases
// @ts-ignore
import type { OperationType } from './operation-type';

export interface AccountOperation {
    /**
     * UUID string
     */
    'operationId': string;
    /**
     * UUID string
     */
    'tradingAccountId': string;
    'operationType': OperationType;
    'status': OperationStatus;
    /**
     * Unix timestamp in milliseconds
     */
    'createdAt': number;
    /**
     * Creation timestamp in ISO 8601 format
     */
    'createdAtDateTime'?: string;
}



