/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthUserAppMetadata } from './auth-user-app-metadata';

/**
 * Authenticated user information
 */
export interface AuthUser {
    /**
     * User ID
     */
    'id'?: string;
    /**
     * User email address
     */
    'email'?: string;
    /**
     * User phone number
     */
    'phone'?: string | null;
    /**
     * Email confirmation timestamp
     */
    'emailConfirmedAt'?: string | null;
    /**
     * Phone confirmation timestamp
     */
    'phoneConfirmedAt'?: string | null;
    /**
     * Last sign in timestamp
     */
    'lastSignInAt'?: string | null;
    /**
     * User role
     */
    'role'?: string;
    /**
     * Account creation timestamp
     */
    'createdAt'?: string;
    /**
     * Account last update timestamp
     */
    'updatedAt'?: string;
    'appMetadata'?: AuthUserAppMetadata;
    /**
     * User-defined metadata
     */
    'userMetadata'?: { [key: string]: any; };
}

