/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AuthUserIdentitiesInner {
    /**
     * Identity ID
     */
    'id'?: string;
    /**
     * User ID
     */
    'userId'?: string;
    /**
     * Identity provider data
     */
    'identityData'?: { [key: string]: any; };
    /**
     * Identity provider name (email, google, etc.)
     */
    'provider'?: string;
    /**
     * Last sign in timestamp for this identity
     */
    'lastSignInAt'?: string | null;
    /**
     * Identity creation timestamp
     */
    'createdAt'?: string;
    /**
     * Identity last update timestamp
     */
    'updatedAt'?: string;
}

