/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthUser } from './auth-user';

/**
 * Authentication session with tokens
 */
export interface AuthSession {
    /**
     * JWT access token
     */
    'accessToken'?: string;
    /**
     * Refresh token for obtaining new access tokens
     */
    'refreshToken'?: string;
    /**
     * Token type
     */
    'tokenType'?: string;
    /**
     * Token expiry in seconds
     */
    'expiresIn'?: number;
    /**
     * Token expiry timestamp (Unix seconds)
     */
    'expiresAt'?: number;
    'user'?: AuthUser;
}

