/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Additional error details (optional, only present in error responses)
 */
export interface BaseResponseDetails {
    /**
     * Error code identifier (e.g., INVALID_TOKEN, ACCESS_DENIED)
     */
    'code'?: string;
    /**
     * Resource that was being accessed
     */
    'resource'?: string;
    /**
     * Action that was being attempted
     */
    'action'?: string;
    /**
     * Required permissions or roles
     */
    'required'?: Array<string>;
    /**
     * Provided permissions or roles
     */
    'provided'?: Array<string>;
    /**
     * Tenant ID if relevant to the error
     */
    'tenant_id'?: string;
    /**
     * Request ID for tracking and debugging
     */
    'request_id'?: string;
    /**
     * Additional metadata as key-value pairs
     */
    'metadata'?: { [key: string]: any; };
}

