/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Venue } from './venue';

/**
 * Connect a trading account. For exchange venues, credentialIds and externalTradingAccountId are required. For Fermata venue, only venue is required (no credentials).
 */
export interface ConnectTradingAccountRequest {
    'venue'?: Venue;
    /**
     * Credential IDs for exchange venues. Not required for Fermata.
     */
    'credentialIds'?: Array<string>;
    /**
     * External trading account ID. Not required for Fermata.
     */
    'externalTradingAccountId'?: string;
    /**
     * UUID string
     */
    'dealerAccountId'?: string;
    /**
     * Nickname of the trading account
     */
    'nickname'?: string;
}



