/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Status of the credential
 */

export const CredentialStatus = {
    Created: 'CREATED',
    Validated: 'VALIDATED',
    Inactive: 'INACTIVE',
    Revoked: 'REVOKED',
    Error: 'ERROR',
    Unknown: 'UNKNOWN'
} as const;

export type CredentialStatus = typeof CredentialStatus[keyof typeof CredentialStatus];



