/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WalletStatus } from './wallet-status';
// May contain unused imports in some cases
// @ts-ignore
import type { WalletType } from './wallet-type';

/**
 * Fermata wallet entity
 */
export interface FermataWallet {
    /**
     * UUID string
     */
    'walletId': string;
    'walletType': WalletType;
    'status': WalletStatus;
    /**
     * Whether this wallet allows negative balances (e.g., dealer short positions)
     */
    'allowNegative'?: boolean;
    /**
     * Additional attributes (name, created_by, etc.)
     */
    'metadata'?: { [key: string]: string; };
    /**
     * Unix timestamp in milliseconds
     */
    'createdAt': number;
    /**
     * Wallet creation timestamp in ISO 8601 format
     */
    'createdAtDateTime'?: string;
    /**
     * Unix timestamp in milliseconds
     */
    'updatedAt': number;
    /**
     * Last update timestamp in ISO 8601 format
     */
    'updatedAtDateTime'?: string;
}



