/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Link an exchange trading account to a dealer as a liquidity provider
 */
export interface FermataLinkDealerRequest {
    /**
     * UUID string
     */
    'dealerAccountId': string;
    /**
     * UUID string
     */
    'tradingAccountId': string;
}

