/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DealerStatus } from './dealer-status';

/**
 * Fermata dealer entity — a principal trading counterparty in the Fermata venue
 */
export interface FermataDealer {
    /**
     * UUID string
     */
    'dealerAccountId': string;
    /**
     * Human-readable dealer name
     */
    'name': string;
    'status': DealerStatus;
    /**
     * Base currencies the dealer settles in
     */
    'baseCurrencies': Array<string>;
    /**
     * Positive decimal value as string
     */
    'riskThreshold'?: string;
    /**
     * Trading account IDs of exchange accounts linked as liquidity providers
     */
    'linkedAccountIds'?: Array<string>;
    /**
     * Additional dealer configuration (spreads, fees, etc.)
     */
    'config'?: { [key: string]: any; };
    /**
     * Unix timestamp in milliseconds
     */
    'createdAt': number;
    /**
     * Creation timestamp in ISO 8601 format
     */
    'createdAtDateTime'?: string;
    /**
     * Unix timestamp in milliseconds
     */
    'updatedAt': number;
    /**
     * Last update timestamp in ISO 8601 format
     */
    'updatedAtDateTime'?: string;
}



