/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SecurityType } from './security-type';
// May contain unused imports in some cases
// @ts-ignore
import type { Venue } from './venue';

export interface FinancialSecurity {
    /**
     * Security ID, id in the format of venue:symbol
     */
    'securityId'?: string;
    /**
     * Symbol
     */
    'symbol'?: string;
    'venue'?: Venue;
    'securityType'?: SecurityType;
    /**
     * Precision
     */
    'precision'?: number;
    /**
     * Scale
     */
    'scale'?: number;
    /**
     * Decimal value as string to preserve precision
     */
    'minQuantity'?: string;
    /**
     * Decimal value as string to preserve precision
     */
    'lotSize'?: string;
}



