/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { HealthCheckComponent } from './health-check-component';
// May contain unused imports in some cases
// @ts-ignore
import type { HealthStatus } from './health-status';

export interface Health503Response {
    'status'?: HealthStatus;
    'timestamp'?: number;
    'timestampISO'?: string;
    'version'?: string;
    /**
     * Details about failed health checks
     */
    'checks'?: { [key: string]: HealthCheckComponent; };
}



