/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { KlineInterval } from './kline-interval';
// May contain unused imports in some cases
// @ts-ignore
import type { Venue } from './venue';

/**
 * Unified kline payload. Used identically in REST responses (`GET /api/v3/market/kline/list`), WebSocket RPC results (`query.kline.list`), and Centrifugo channel publications (`market:kline:{venue}:{symbol}:{interval}`).  Each candle is a fixed-position OHLCV tuple (no `columns` field). REST returns `isClosed: true` for historical-only queries; `isClosed: false` only when the queried range includes the live bar. Streaming surfaces emit `false` while the current bar is forming and `true` when it closes. 
 */
export interface Kline {
    /**
     * Instrument ID in format {VENUE}:{BASE}/{QUOTE}
     */
    'instrumentId'?: string;
    'venue': Venue;
    /**
     * Trading pair symbol in format {BASE}/{QUOTE}
     */
    'symbol': string;
    'interval': KlineInterval;
    /**
     * OHLCV tuples ordered ascending by `openTime`.
     */
    'candles': Array<Array<any>>;
    /**
     * Whether the **last** candle in `candles` is finalized. Historical candles before the last are always closed. 
     */
    'isClosed': boolean;
    /**
     * Unix timestamp in milliseconds
     */
    'timestamp': number;
}



