/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Kline (candlestick) interval. Not all venues support every interval — refer to the venue\'s connector for the supported set.
 */

export const KlineInterval = {
    _1s: '1s',
    _1m: '1m',
    _3m: '3m',
    _5m: '5m',
    _15m: '15m',
    _30m: '30m',
    _1h: '1h',
    _2h: '2h',
    _4h: '4h',
    _6h: '6h',
    _8h: '8h',
    _12h: '12h',
    _1d: '1d',
    _3d: '3d',
    _1w: '1w',
    _1M: '1M',
} as const;

export type KlineInterval = typeof KlineInterval[keyof typeof KlineInterval];



