/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Operation type
 */

export const OperationType = {
    Connect: 'CONNECT',
    Disconnect: 'DISCONNECT',
    Enable: 'ENABLE',
    Disable: 'DISABLE',
    Update: 'UPDATE',
    CredentialRevoke: 'CREDENTIAL_REVOKE',
    CredentialRotate: 'CREDENTIAL_ROTATE'
} as const;

export type OperationType = typeof OperationType[keyof typeof OperationType];



