/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Order type
 */

export const OrderType = {
    Empty: '',
    Market: 'MARKET',
    Limit: 'LIMIT',
    StopLoss: 'STOP_LOSS',
    StopLossLimit: 'STOP_LOSS_LIMIT',
    TakeProfit: 'TAKE_PROFIT',
    TakeProfitLimit: 'TAKE_PROFIT_LIMIT',
    Quoted: 'QUOTED'
} as const;

export type OrderType = typeof OrderType[keyof typeof OrderType];



