/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Order status
 */

export const OrderStatus = {
    Empty: '',
    Created: 'CREATED',
    Submitted: 'SUBMITTED',
    Accepted: 'ACCEPTED',
    PartiallyFilled: 'PARTIALLY_FILLED',
    Filled: 'FILLED',
    Cancelled: 'CANCELLED',
    PendingCancel: 'PENDING_CANCEL',
    Replaced: 'REPLACED',
    PendingReplace: 'PENDING_REPLACE',
    Rejected: 'REJECTED',
    Expired: 'EXPIRED',
    Revoked: 'REVOKED',
    Unknown: 'UNKNOWN'
} as const;

export type OrderStatus = typeof OrderStatus[keyof typeof OrderStatus];



