/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Order side (buy or sell)
 */

export const OrderSide = {
    Buy: 'BUY',
    Sell: 'SELL',
    Unknown: 'UNKNOWN'
} as const;

export type OrderSide = typeof OrderSide[keyof typeof OrderSide];



