/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Pagination parameters and metadata
 */
export interface Pagination {
    /**
     * Number of items to skip
     */
    'offset'?: number;
    /**
     * Maximum number of items to return
     */
    'limit'?: number;
    /**
     * Total number of items available
     */
    'total'?: number;
    /**
     * Cursor for next page (optional)
     */
    'cursor'?: string;
    /**
     * Whether there are more items
     */
    'hasNext'?: boolean;
}

