/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BalanceEntry } from './balance-entry';
// May contain unused imports in some cases
// @ts-ignore
import type { PortfolioSummary } from './portfolio-summary';
// May contain unused imports in some cases
// @ts-ignore
import type { PositionEntry } from './position-entry';
// May contain unused imports in some cases
// @ts-ignore
import type { Venue } from './venue';

export interface Portfolio {
    /**
     * UUID string
     */
    'tradingAccountId': string;
    'venue': Venue;
    'positions': Array<PositionEntry>;
    'balances': Array<BalanceEntry>;
    'summary': PortfolioSummary;
    /**
     * Unix timestamp in milliseconds
     */
    'updatedAt': number;
    /**
     * Last update timestamp in ISO 8601 format
     */
    'updatedAtDateTime'?: string;
}



