/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PortfolioSummary {
    /**
     * UUID string
     */
    'tradingAccountId': string;
    /**
     * Base currency for the portfolio summary
     */
    'currency': string;
    /**
     * Leverage multiplier
     */
    'leverage': number | null;
    /**
     * Decimal value as string to preserve precision
     */
    'equity': string;
    /**
     * Decimal value as string to preserve precision
     */
    'margin': string;
    /**
     * Decimal value as string to preserve precision
     */
    'marginLoan': string;
    /**
     * Decimal value as string to preserve precision
     */
    'marginUsage': string;
    /**
     * Decimal value as string to preserve precision
     */
    'marginRequirement': string;
    /**
     * Decimal value as string to preserve precision
     */
    'marginLevel': string;
    /**
     * Decimal value as string to preserve precision
     */
    'credit': string;
    /**
     * Decimal value as string to preserve precision
     */
    'riskExposure': string;
    /**
     * Decimal value as string to preserve precision
     */
    'maxRiskExposure'?: string;
    /**
     * Decimal value as string to preserve precision
     */
    'riskExposureRate'?: string;
}

