/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PositionStatus } from './position-status';
// May contain unused imports in some cases
// @ts-ignore
import type { SecurityType } from './security-type';

export interface PositionEntry {
    /**
     * UUID string
     */
    'positionId': string;
    /**
     * Security symbol
     */
    'securitySymbol': string;
    /**
     * External position ID from the exchange
     */
    'externalPositionId'?: string | null;
    /**
     * UUID string
     */
    'tradingAccountId': string;
    /**
     * Instrument ID in format {VENUE}:{BASE}/{QUOTE}
     */
    'instrumentId'?: string;
    'securityType': SecurityType;
    'status': PositionStatus;
    /**
     * Decimal value as string to preserve precision
     */
    'quantity': string;
    /**
     * Decimal value as string to preserve precision
     */
    'entryPrice'?: string;
    /**
     * Decimal value as string to preserve precision
     */
    'exitPrice'?: string;
    /**
     * Decimal value as string to preserve precision
     */
    'currentPrice'?: string;
    /**
     * Decimal value as string to preserve precision
     */
    'unrealizedPnl'?: string;
    /**
     * Decimal value as string to preserve precision
     */
    'realizedPnl'?: string;
    /**
     * Unix timestamp in milliseconds
     */
    'createdAt': number;
    /**
     * Creation timestamp in ISO 8601 format
     */
    'createdAtDateTime'?: string;
    /**
     * Unix timestamp in milliseconds
     */
    'updatedAt': number;
    /**
     * Last update timestamp in ISO 8601 format
     */
    'updatedAtDateTime'?: string;
    /**
     * Unix timestamp in milliseconds
     */
    'closedAt'?: number;
    /**
     * Position closure timestamp in ISO 8601 format
     */
    'closedAtDateTime'?: string | null;
}



