/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Quantity rounding strategy to meet lot size requirements. Empty string means no rounding (rejects orders that don\'t meet lot size requirements).
 */

export const QuantityRounding = {
    Empty: '',
    Up: 'UP',
    Down: 'DOWN',
    Nearest: 'NEAREST',
    Ceil: 'CEIL',
    Floor: 'FLOOR',
    HalfUp: 'HALF_UP',
    HalfDown: 'HALF_DOWN',
    HalfEven: 'HALF_EVEN'
} as const;

export type QuantityRounding = typeof QuantityRounding[keyof typeof QuantityRounding];



