/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OrderSide } from './order-side';

/**
 * Request a firm quote. Supports any venue with RFQ capability — use instrumentId for venues that identify pairs by ID, or baseAsset/quoteAsset for symbol-based venues.
 */
export interface QuoteRfqRequest {
    /**
     * UUID string
     */
    'dealerAccountId': string;
    /**
     * UUID string
     */
    'traderAccountId'?: string;
    /**
     * Instrument ID in format {VENUE}:{BASE}/{QUOTE}
     */
    'instrumentId'?: string;
    /**
     * Asset symbol (e.g. currency code, base asset)
     */
    'baseAsset'?: string;
    /**
     * Asset symbol (e.g. currency code, base asset)
     */
    'quoteAsset'?: string;
    'orderSide': OrderSide;
    /**
     * Positive decimal value as string
     */
    'quantity'?: string;
    /**
     * Positive decimal value as string
     */
    'quoteQuantity'?: string;
    /**
     * Client-provided reference for idempotency and tracking
     */
    'quoteRequestId'?: string;
    /**
     * Time to live in seconds
     */
    'ttl'?: number;
    /**
     * Absolute expiry timestamp (ISO 8601). Mutually exclusive with ttl. If neither ttl nor expireAt is set, defaults to 10 seconds from quote creation.
     */
    'expireAt'?: string;
    /**
     * UUID string
     */
    'pricingProfileId'?: string;
}



