/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RpcOrderBookLevel } from './rpc-order-book-level';

/**
 * Order book model
 */
export interface RpcOrderBook {
    /**
     * Instrument ID
     */
    'instrumentId'?: string;
    /**
     * Venue
     */
    'venue'?: string;
    /**
     * Trading pair symbol
     */
    'symbol'?: string;
    /**
     * Bid orders (sorted by price descending)
     */
    'bids'?: Array<RpcOrderBookLevel>;
    /**
     * Ask orders (sorted by price ascending)
     */
    'asks'?: Array<RpcOrderBookLevel>;
    /**
     * Timestamp in ISO 8601 format (RFC3339). This is the native format used by Go\'s time.Time.
     */
    'timestamp'?: string;
    /**
     * Sequence number for ordering updates
     */
    'sequenceNumber'?: number;
}

