/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request to list order books for multiple instruments
 */
export interface RpcListOrderBooksParams {
    /**
     * List of instrument IDs
     */
    'instrumentIds'?: Array<string>;
    /**
     * Filter by venue
     */
    'venue'?: string;
    /**
     * List of symbols
     */
    'symbols'?: Array<string>;
    /**
     * Order book depth
     */
    'depth'?: number;
}

