/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Portfolio summary with aggregated metrics
 */
export interface RpcPortfolioSummary {
    'portfolioSummaryId'?: string;
    'tradingAccountId'?: string;
    /**
     * Summary currency
     */
    'currency'?: string;
    'leverage'?: number;
    /**
     * Total equity
     */
    'equity'?: string;
    /**
     * Margin collateral
     */
    'margin'?: string;
    /**
     * Borrowed margin
     */
    'marginLoan'?: string;
    /**
     * Margin usage rate
     */
    'marginUsage'?: string;
    /**
     * Required margin
     */
    'marginRequirement'?: string;
    /**
     * Margin level
     */
    'marginLevel'?: string;
    /**
     * Available credit
     */
    'credit'?: string;
    /**
     * Total risk exposure
     */
    'riskExposure'?: string;
    /**
     * Maximum risk exposure
     */
    'maxRiskExposure'?: string;
    /**
     * Risk exposure rate
     */
    'riskExposureRate'?: string;
}

