/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RpcTradeOrder } from './rpc-trade-order';

/**
 * Request to submit a new trade order
 */
export interface RpcSubmitTradeOrderRequest {
    'tradeOrder': RpcTradeOrder;
    /**
     * Trading account ID to place order on
     */
    'tradingAccountId': string;
    /**
     * Idempotency key to prevent duplicate orders
     */
    'idempotencyKey'?: string;
    /**
     * Wait for order to reach terminal state before responding
     */
    'awaitClosed'?: boolean;
}

