/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { InstrumentStatus } from './instrument-status';
// May contain unused imports in some cases
// @ts-ignore
import type { InstrumentType } from './instrument-type';
// May contain unused imports in some cases
// @ts-ignore
import type { SecurityType } from './security-type';
// May contain unused imports in some cases
// @ts-ignore
import type { Venue } from './venue';

/**
 * Financial instrument
 */
export interface RpcInstrument {
    /**
     * Unique instrument identifier (format: VENUE:BASE/QUOTE)
     */
    'instrumentId'?: string;
    'venue'?: Venue;
    'symbol'?: string;
    'externalSymbol'?: string;
    'description'?: string;
    'instrumentType'?: InstrumentType;
    'status'?: InstrumentStatus;
    'baseAsset'?: string;
    'quoteAsset'?: string;
    'baseSecurityType'?: SecurityType;
    'quoteSecurityType'?: SecurityType;
    'basePrecision'?: number;
    'quotePrecision'?: number;
    /**
     * Decimal value as string
     */
    'lotSize'?: string;
    /**
     * Decimal value as string
     */
    'pipSize'?: string;
    /**
     * Decimal value as string
     */
    'minQuantity'?: string;
    /**
     * Decimal value as string
     */
    'maxQuantity'?: string;
    /**
     * Decimal value as string
     */
    'minNotional'?: string;
    /**
     * Decimal value as string
     */
    'maxNotional'?: string;
    'orderTypes'?: Array<string>;
    'timeInForceOptions'?: Array<string>;
    /**
     * Decimal value as string
     */
    'fee'?: string;
    'isIcebergAllowed'?: boolean;
    /**
     * Decimal value as string
     */
    'contractSize'?: string;
    'createdAt'?: string;
    'updatedAt'?: string;
}



