/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Market ticker data
 */
export interface RpcTicker {
    'instrumentId'?: string;
    'symbol'?: string;
    'exchange'?: string;
    'exchangeTime'?: string;
    'time'?: string;
    /**
     * Ask price (decimal)
     */
    'ask'?: string;
    /**
     * Ask quantity (decimal)
     */
    'askQuantity'?: string;
    /**
     * Bid price (decimal)
     */
    'bid'?: string;
    /**
     * Bid quantity (decimal)
     */
    'bidQuantity'?: string;
    /**
     * Last price (decimal)
     */
    'last'?: string;
    /**
     * Last quantity (decimal)
     */
    'lastQuantity'?: string;
}

