/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CredentialStatus } from './credential-status';
// May contain unused imports in some cases
// @ts-ignore
import type { CredentialType } from './credential-type';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcPagination } from './rpc-pagination';
// May contain unused imports in some cases
// @ts-ignore
import type { Venue } from './venue';

/**
 * Request to list credentials
 */
export interface RpcListCredentialsRequest {
    'credentialIds'?: Array<string>;
    'venue'?: Venue;
    'credentialType'?: CredentialType;
    'status'?: CredentialStatus;
    'pagination'?: RpcPagination;
}



