/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BalanceStatus } from './balance-status';
// May contain unused imports in some cases
// @ts-ignore
import type { SecurityType } from './security-type';

/**
 * Balance entry for an asset
 */
export interface RpcBalanceEntry {
    'balanceId'?: string;
    'externalBalanceId'?: string;
    'tradingAccountId'?: string;
    /**
     * Asset symbol
     */
    'securitySymbol'?: string;
    'securityType'?: SecurityType;
    'status'?: BalanceStatus;
    /**
     * Available balance
     */
    'free'?: string;
    /**
     * Locked balance
     */
    'locked'?: string;
    /**
     * Frozen balance
     */
    'frozen'?: string;
    /**
     * Borrowed amount
     */
    'borrowed'?: string;
    /**
     * Interest owed
     */
    'interestOwed'?: string;
    /**
     * Total balance
     */
    'total'?: string;
    /**
     * Net equity
     */
    'net'?: string;
    'collateralWeight'?: string;
    'collateralValue'?: string;
    'collateralEnabled'?: boolean;
    'crossMargin'?: string;
    'isolatedMargin'?: string;
    'marginRatio'?: string;
    'createdAt'?: string;
    'updatedAt'?: string;
}



