/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Health200ResponseChecks } from './health200-response-checks';
// May contain unused imports in some cases
// @ts-ignore
import type { HealthStatus } from './health-status';

/**
 * Health check data
 */
export interface RpcHealthCheck {
    'status': HealthStatus;
    /**
     * Timestamp in ISO 8601 format (RFC3339). This is the native format used by Go\'s time.Time.
     */
    'timestamp': string;
    /**
     * API version
     */
    'version': string;
    'checks'?: Health200ResponseChecks;
}



