/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OrderSide } from './order-side';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderStatus } from './order-status';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderType } from './order-type';
// May contain unused imports in some cases
// @ts-ignore
import type { QuantityRounding } from './quantity-rounding';
// May contain unused imports in some cases
// @ts-ignore
import type { QuantityType } from './quantity-type';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSecurityQuantity } from './rpc-security-quantity';
// May contain unused imports in some cases
// @ts-ignore
import type { TimeInForce } from './time-in-force';

/**
 * Trade order model
 */
export interface RpcTradeOrder {
    /**
     * Unique trade order ID
     */
    'tradeOrderId'?: string;
    /**
     * Client-assigned order ID
     */
    'clientOrderId'?: string;
    /**
     * Original client order ID (for cancel/replace)
     */
    'originalClientOrderId'?: string;
    /**
     * Order ID from external venue
     */
    'externalOrderId'?: string;
    /**
     * Idempotency key
     */
    'idempotencyKey'?: string;
    /**
     * Trading venue
     */
    'venue'?: string;
    /**
     * Trading account ID
     */
    'tradingAccountId'?: string;
    /**
     * External account ID at venue
     */
    'externalTradingAccountId'?: string;
    /**
     * Instrument ID (VENUE:BASE/QUOTE)
     */
    'instrumentId'?: string;
    /**
     * Symbol at external venue
     */
    'externalSymbol'?: string;
    /**
     * Base asset
     */
    'baseAsset'?: string;
    /**
     * Quote asset
     */
    'quoteAsset'?: string;
    'orderType'?: OrderType;
    'orderSide'?: OrderSide;
    'quantityType'?: QuantityType;
    /**
     * Order quantity (decimal string)
     */
    'quantity'?: string;
    /**
     * Quantity in quote currency
     */
    'quoteCurrencyQuantity'?: string;
    /**
     * Quantity as position percentage
     */
    'positionPercentage'?: string;
    'quantityRounding'?: QuantityRounding;
    /**
     * Limit price (decimal string)
     */
    'limitPrice'?: string;
    /**
     * Stop price (decimal string)
     */
    'stopPrice'?: string;
    'timeInForce'?: TimeInForce;
    'status'?: OrderStatus;
    /**
     * Average executed price
     */
    'executedPrice'?: string;
    /**
     * Percentage of order filled
     */
    'executedPercentage'?: string;
    /**
     * Quantity executed
     */
    'executedQuantity'?: string;
    /**
     * Total cost in quote currency
     */
    'executedCost'?: string;
    /**
     * Fees charged
     */
    'fees'?: Array<RpcSecurityQuantity>;
    /**
     * Reason for cancellation
     */
    'cancelReason'?: string;
    /**
     * Reason for rejection
     */
    'rejectReason'?: string;
    /**
     * Order creation time
     */
    'createdAt'?: string;
    /**
     * Last update time
     */
    'updatedAt'?: string;
    /**
     * Order expiration time (for GTD)
     */
    'expireAt'?: string;
    /**
     * Time of last execution
     */
    'lastExecutionAt'?: string;
    /**
     * Time of cancellation
     */
    'canceledAt'?: string;
}



