/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Type of security (base asset)
 */

export const SecurityType = {
    Empty: '',
    Cash: 'CASH',
    Stock: 'STOCK',
    Crypto: 'CRYPTO',
    Currency: 'CURRENCY',
    Commodity: 'COMMODITY',
    Index: 'INDEX',
    Bond: 'BOND',
    Derivative: 'DERIVATIVE',
    Option: 'OPTION',
    Future: 'FUTURE',
    Futures: 'FUTURES',
    Perpetual: 'PERPETUAL',
    Forex: 'FOREX'
} as const;

export type SecurityType = typeof SecurityType[keyof typeof SecurityType];



