/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Type of data subscription. Format: `{LEVEL}.SUBSCRIPTION.{TYPE}`.  Market-level subscriptions stream public market data; trading-account-level subscriptions stream account-scoped data.  `TRADING_ACCOUNT.SUBSCRIPTION.TRADING_ACCOUNT` is deprecated — use `TRADING_ACCOUNT.SUBSCRIPTION.USER_DATA` instead (which combines `PORTFOLIO` and `EXECUTION_REPORT`). 
 */

export const SubscriptionType = {
    MarketSubscriptionOrderbook: 'MARKET.SUBSCRIPTION.ORDERBOOK',
    MarketSubscriptionTrade: 'MARKET.SUBSCRIPTION.TRADE',
    MarketSubscriptionTicker: 'MARKET.SUBSCRIPTION.TICKER',
    MarketSubscriptionKline: 'MARKET.SUBSCRIPTION.KLINE',
    TradingAccountSubscriptionUserData: 'TRADING_ACCOUNT.SUBSCRIPTION.USER_DATA',
    TradingAccountSubscriptionPortfolio: 'TRADING_ACCOUNT.SUBSCRIPTION.PORTFOLIO',
    TradingAccountSubscriptionExecutionReport: 'TRADING_ACCOUNT.SUBSCRIPTION.EXECUTION_REPORT',
    TradingAccountSubscriptionTradingAccount: 'TRADING_ACCOUNT.SUBSCRIPTION.TRADING_ACCOUNT',
} as const;

export type SubscriptionType = typeof SubscriptionType[keyof typeof SubscriptionType];



