/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Type of data subscription
 */

export const SubscriptionType = {
    Orderbook: 'ORDERBOOK',
    Trade: 'TRADE',
    Ticker: 'TICKER',
    Kline: 'KLINE',
    UserData: 'USER_DATA',
    Portfolio: 'PORTFOLIO',
    ExecutionReport: 'EXECUTION_REPORT',
    TradingAccount: 'TRADING_ACCOUNT'
} as const;

export type SubscriptionType = typeof SubscriptionType[keyof typeof SubscriptionType];



