/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SubscriptionStatus } from './subscription-status';
// May contain unused imports in some cases
// @ts-ignore
import type { SubscriptionType } from './subscription-type';
// May contain unused imports in some cases
// @ts-ignore
import type { Venue } from './venue';

export interface Subscription {
    /**
     * UUID string
     */
    'subscriptionId': string;
    'venue': Venue;
    /**
     * UUID string
     */
    'tradingAccountId'?: string;
    /**
     * Instrument ID in format {VENUE}:{BASE}/{QUOTE}
     */
    'instrumentId'?: string;
    'subscriptionType': SubscriptionType;
    'status': SubscriptionStatus;
    /**
     * Unix timestamp in milliseconds
     */
    'createdAt': number;
    /**
     * Creation timestamp in ISO 8601 format
     */
    'createdAtDateTime'?: string;
    /**
     * Unix timestamp in milliseconds
     */
    'updatedAt': number;
    /**
     * Last update timestamp in ISO 8601 format
     */
    'updatedAtDateTime'?: string;
    /**
     * Unix timestamp in milliseconds
     */
    'lastEventTimestamp'?: number;
}



