/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Venue } from './venue';

/**
 * Unified ticker payload. Used identically in REST responses (`GET /api/v3/market/ticker/_*`), WebSocket RPC results (`query.ticker.get` / `query.ticker.list`), and Centrifugo channel publications (`market:ticker:{venue}:{symbol}`, `market:ticker:{venue}`). 
 */
export interface Ticker {
    /**
     * Instrument ID in format {VENUE}:{BASE}/{QUOTE}
     */
    'instrumentId'?: string;
    'venue': Venue;
    /**
     * Trading pair symbol in format {BASE}/{QUOTE}
     */
    'symbol': string;
    /**
     * Decimal value as string to preserve precision
     */
    'lastPrice'?: string;
    /**
     * Decimal value as string to preserve precision
     */
    'lastQuantity'?: string;
    /**
     * Decimal value as string to preserve precision
     */
    'bidPrice'?: string;
    /**
     * Decimal value as string to preserve precision
     */
    'bidQuantity'?: string;
    /**
     * Decimal value as string to preserve precision
     */
    'askPrice'?: string;
    /**
     * Decimal value as string to preserve precision
     */
    'askQuantity'?: string;
    /**
     * Decimal value as string to preserve precision
     */
    'priceChangePercent'?: string;
    /**
     * Unix timestamp in milliseconds
     */
    'timestamp': number;
}



