/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Time in force - specifies how long an order remains active
 */

export const TimeInForce = {
    Empty: '',
    Gtc: 'GTC',
    Ioc: 'IOC',
    Fok: 'FOK',
    Gtd: 'GTD',
    Day: 'DAY',
    Gtx: 'GTX',
    Opg: 'OPG',
    Cls: 'CLS',
    Gfa: 'GFA',
    Gfs: 'GFS',
    Gtm: 'GTM',
    Moo: 'MOO',
    Moc: 'MOC',
    Ext: 'EXT',
    Unknown: 'UNKNOWN'
} as const;

export type TimeInForce = typeof TimeInForce[keyof typeof TimeInForce];



