/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AccountType } from './account-type';
// May contain unused imports in some cases
// @ts-ignore
import type { CollateralMode } from './collateral-mode';
// May contain unused imports in some cases
// @ts-ignore
import type { MarginMode } from './margin-mode';
// May contain unused imports in some cases
// @ts-ignore
import type { PositionMode } from './position-mode';
// May contain unused imports in some cases
// @ts-ignore
import type { TradingAccountCredential } from './trading-account-credential';
// May contain unused imports in some cases
// @ts-ignore
import type { TradingAccountStatus } from './trading-account-status';
// May contain unused imports in some cases
// @ts-ignore
import type { Venue } from './venue';

export interface TradingAccount {
    /**
     * UUID string
     */
    'tradingAccountId': string;
    /**
     * External trading account ID
     */
    'externalTradingAccountId': string;
    'venue': Venue;
    /**
     * Nickname of the trading account
     */
    'nickname': string;
    'accountType': AccountType;
    /**
     * Type of account on the exchange (set by market connector)
     */
    'externalAccountType': string;
    'positionMode'?: PositionMode;
    'collateralMode'?: CollateralMode;
    'marginMode'?: MarginMode;
    'credentials': Array<TradingAccountCredential>;
    'status': TradingAccountStatus;
    /**
     * Unix timestamp in milliseconds
     */
    'createdAt': number;
    /**
     * Creation timestamp in ISO 8601 format
     */
    'createdAtDateTime'?: string;
    /**
     * Unix timestamp in milliseconds
     */
    'updatedAt': number;
    /**
     * Last update timestamp in ISO 8601 format
     */
    'updatedAtDateTime'?: string;
}



