/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OrderQuantityType } from './order-quantity-type';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderSide } from './order-side';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderStatus } from './order-status';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderType } from './order-type';
// May contain unused imports in some cases
// @ts-ignore
import type { QuantityRounding } from './quantity-rounding';
// May contain unused imports in some cases
// @ts-ignore
import type { SecurityQuantity } from './security-quantity';
// May contain unused imports in some cases
// @ts-ignore
import type { TimeInForce } from './time-in-force';
// May contain unused imports in some cases
// @ts-ignore
import type { TradeExecution } from './trade-execution';
// May contain unused imports in some cases
// @ts-ignore
import type { Venue } from './venue';

export interface TradeOrder {
    /**
     * UUID string
     */
    'tradeOrderId': string;
    /**
     * UUID string
     */
    'tradingAccountId': string;
    'venue': Venue;
    /**
     * UUID string
     */
    'positionId'?: string;
    /**
     * Instrument ID in format {VENUE}:{BASE}/{QUOTE}
     */
    'instrumentId': string;
    /**
     * UUID string
     */
    'quoteId'?: string;
    /**
     * Base asset in the trading pair
     */
    'baseAsset': string;
    /**
     * Quote asset in the trading pair
     */
    'quoteAsset': string;
    'orderSide': OrderSide;
    'orderType': OrderType;
    'timeInForce': TimeInForce;
    'status': OrderStatus;
    /**
     * Reason for order rejection
     */
    'rejectReason'?: string;
    /**
     * Reason for order cancellation
     */
    'cancelReason'?: string;
    /**
     * Decimal value as string to preserve precision
     */
    'limitPrice'?: string;
    /**
     * Decimal value as string to preserve precision
     */
    'stopPrice'?: string;
    /**
     * Decimal value as string to preserve precision
     */
    'quantity': string;
    'orderQuantityType': OrderQuantityType;
    'quantityRounding'?: QuantityRounding;
    /**
     * Decimal value as string to preserve precision
     */
    'executedPrice': string;
    /**
     * Decimal value as string to preserve precision
     */
    'executedQuantity': string;
    /**
     * Decimal value as string to preserve precision
     */
    'executedCost': string;
    /**
     * Aggregated fees across all executions
     */
    'fees': Array<SecurityQuantity>;
    /**
     * Detailed breakdown of executions across different venues
     */
    'executions'?: Array<TradeExecution>;
    /**
     * Unix timestamp in milliseconds
     */
    'createdAt': number;
    /**
     * Creation timestamp in ISO 8601 format
     */
    'createdAtDateTime'?: string;
    /**
     * Unix timestamp in milliseconds
     */
    'updatedAt': number;
    /**
     * Last update timestamp in ISO 8601 format
     */
    'updatedAtDateTime'?: string;
    /**
     * Unix timestamp in milliseconds
     */
    'expireAt'?: number;
    /**
     * Expiration timestamp in ISO 8601 format
     */
    'expireAtDateTime'?: string;
    /**
     * Unix timestamp in milliseconds
     */
    'canceledAt'?: number;
    /**
     * Cancellation timestamp in ISO 8601 format
     */
    'canceledAtDateTime'?: string;
}



