/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Type of trading account operation
 */

export const TradingAccountOperationType = {
    Connect: 'CONNECT',
    Connected: 'CONNECTED',
    Disconnect: 'DISCONNECT',
    Disconnected: 'DISCONNECTED',
    Enable: 'ENABLE',
    Enabled: 'ENABLED',
    Disable: 'DISABLE',
    Disabled: 'DISABLED',
    Deleted: 'DELETED'
} as const;

export type TradingAccountOperationType = typeof TradingAccountOperationType[keyof typeof TradingAccountOperationType];



