/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Trading venue identifier. UAT/sandbox environments are treated as separate venues. Note: _SANDBOX and _PAPER suffixes are deprecated. Use _UAT suffix for new integrations. 
 */

export const Venue = {
    Empty: '',
    Binance: 'BINANCE',
    B2C2: 'B2C2',
    Wintermute: 'WINTERMUTE',
    Blockfills: 'BLOCKFILLS',
    Stonex: 'STONEX',
    Cumberland: 'CUMBERLAND',
    Ibkr: 'IBKR',
    Deribit: 'DERIBIT',
    Bitfinex: 'BITFINEX',
    Okx: 'OKX',
    BinanceUat: 'BINANCE_UAT',
    B2C2Uat: 'B2C2_UAT',
    WintermuteUat: 'WINTERMUTE_UAT',
    BlockfillsUat: 'BLOCKFILLS_UAT',
    StonexUat: 'STONEX_UAT',
    CumberlandUat: 'CUMBERLAND_UAT',
    IbkrUat: 'IBKR_UAT',
    DeribitUat: 'DERIBIT_UAT',
    BitfinexUat: 'BITFINEX_UAT',
    OkxUat: 'OKX_UAT',
    BinanceSandbox: 'BINANCE_SANDBOX',
    B2C2Sandbox: 'B2C2_SANDBOX',
    IbkrPaper: 'IBKR_PAPER',
    Mock: 'MOCK',
    Paper: 'PAPER'
} as const;

export type Venue = typeof Venue[keyof typeof Venue];



