/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BaseResponse } from './base-response';
// May contain unused imports in some cases
// @ts-ignore
import type { BaseResponseDetails } from './base-response-details';
// May contain unused imports in some cases
// @ts-ignore
import type { TradingAccount } from './trading-account';

/**
 * @type VerifyTradingAccountCredential200Response
 */
export type VerifyTradingAccountCredential200Response = BaseResponse;


