/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WsConnectRequest } from './ws-connect-request';
// May contain unused imports in some cases
// @ts-ignore
import type { WsHistoryRequest } from './ws-history-request';
// May contain unused imports in some cases
// @ts-ignore
import type { WsPresenceRequest } from './ws-presence-request';
// May contain unused imports in some cases
// @ts-ignore
import type { WsPresenceStatsRequest } from './ws-presence-stats-request';
// May contain unused imports in some cases
// @ts-ignore
import type { WsPublishRequest } from './ws-publish-request';
// May contain unused imports in some cases
// @ts-ignore
import type { WsRPCRequest } from './ws-rpcrequest';
// May contain unused imports in some cases
// @ts-ignore
import type { WsRefreshRequest } from './ws-refresh-request';
// May contain unused imports in some cases
// @ts-ignore
import type { WsSendRequest } from './ws-send-request';
// May contain unused imports in some cases
// @ts-ignore
import type { WsSubRefreshRequest } from './ws-sub-refresh-request';
// May contain unused imports in some cases
// @ts-ignore
import type { WsSubscribeRequest } from './ws-subscribe-request';
// May contain unused imports in some cases
// @ts-ignore
import type { WsUnsubscribeRequest } from './ws-unsubscribe-request';

/**
 * WebSocket command sent from client to server. Only one command field should be set per message.
 */
export interface WsCommand {
    /**
     * Unique command ID for request-response correlation
     */
    'id': number;
    'connect'?: WsConnectRequest;
    'subscribe'?: WsSubscribeRequest;
    'unsubscribe'?: WsUnsubscribeRequest;
    'publish'?: WsPublishRequest;
    'presence'?: WsPresenceRequest;
    'presenceStats'?: WsPresenceStatsRequest;
    'history'?: WsHistoryRequest;
    /**
     * Ping request to keep connection alive
     */
    'ping'?: object;
    'send'?: WsSendRequest;
    'rpc'?: WsRPCRequest;
    'refresh'?: WsRefreshRequest;
    'subRefresh'?: WsSubRefreshRequest;
}

