/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * WebSocket error object returned when a command fails
 */
export interface WsError {
    /**
     * Error code
     */
    'code': number;
    /**
     * Error message
     */
    'message': string;
    /**
     * Whether the error is temporary and the command can be retried
     */
    'temporary'?: boolean;
}

