/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WsConnectPush } from './ws-connect-push';
// May contain unused imports in some cases
// @ts-ignore
import type { WsDisconnect } from './ws-disconnect';
// May contain unused imports in some cases
// @ts-ignore
import type { WsJoin } from './ws-join';
// May contain unused imports in some cases
// @ts-ignore
import type { WsLeave } from './ws-leave';
// May contain unused imports in some cases
// @ts-ignore
import type { WsMessage } from './ws-message';
// May contain unused imports in some cases
// @ts-ignore
import type { WsPublication } from './ws-publication';
// May contain unused imports in some cases
// @ts-ignore
import type { WsRefreshPush } from './ws-refresh-push';
// May contain unused imports in some cases
// @ts-ignore
import type { WsSubscribePush } from './ws-subscribe-push';
// May contain unused imports in some cases
// @ts-ignore
import type { WsUnsubscribePush } from './ws-unsubscribe-push';

/**
 * Server push message (asynchronous, id=0 in reply)
 */
export interface WsPush {
    /**
     * Channel the push is for
     */
    'channel'?: string;
    'pub'?: WsPublication;
    'join'?: WsJoin;
    'leave'?: WsLeave;
    'unsubscribe'?: WsUnsubscribePush;
    'message'?: WsMessage;
    'subscribe'?: WsSubscribePush;
    'connect'?: WsConnectPush;
    'disconnect'?: WsDisconnect;
    'refresh'?: WsRefreshPush;
}

