/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WsConnectResult } from './ws-connect-result';
// May contain unused imports in some cases
// @ts-ignore
import type { WsError } from './ws-error';
// May contain unused imports in some cases
// @ts-ignore
import type { WsHistoryResult } from './ws-history-result';
// May contain unused imports in some cases
// @ts-ignore
import type { WsPresenceResult } from './ws-presence-result';
// May contain unused imports in some cases
// @ts-ignore
import type { WsPresenceStatsResult } from './ws-presence-stats-result';
// May contain unused imports in some cases
// @ts-ignore
import type { WsPush } from './ws-push';
// May contain unused imports in some cases
// @ts-ignore
import type { WsRPCResult } from './ws-rpcresult';
// May contain unused imports in some cases
// @ts-ignore
import type { WsRefreshResult } from './ws-refresh-result';
// May contain unused imports in some cases
// @ts-ignore
import type { WsSubRefreshResult } from './ws-sub-refresh-result';
// May contain unused imports in some cases
// @ts-ignore
import type { WsSubscribeResult } from './ws-subscribe-result';

/**
 * WebSocket reply sent from server to client. The id field is zero for server-initiated pushes.
 */
export interface WsReply {
    /**
     * Command ID matching the request (0 for pushes)
     */
    'id'?: number;
    'error'?: WsError;
    'push'?: WsPush;
    'connect'?: WsConnectResult;
    'subscribe'?: WsSubscribeResult;
    /**
     * Unsubscribe result (empty on success)
     */
    'unsubscribe'?: object;
    /**
     * Publish result (empty on success)
     */
    'publish'?: object;
    'presence'?: WsPresenceResult;
    'presenceStats'?: WsPresenceStatsResult;
    'history'?: WsHistoryResult;
    /**
     * Pong response
     */
    'ping'?: object;
    'rpc'?: WsRPCResult;
    'refresh'?: WsRefreshResult;
    'subRefresh'?: WsSubRefreshResult;
}

