/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RpcCancelTradeOrderResult } from './rpc-cancel-trade-order-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcConnectTradingAccountResult } from './rpc-connect-trading-account-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcCreateCredentialResult } from './rpc-create-credential-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcCreateSubscriptionResult } from './rpc-create-subscription-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcCreateTradingAccountResult } from './rpc-create-trading-account-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcDeleteInstrumentResult } from './rpc-delete-instrument-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcDeleteSecuritiesResult } from './rpc-delete-securities-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcDeleteTradingAccountResult } from './rpc-delete-trading-account-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcDisableInstrumentResult } from './rpc-disable-instrument-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcDisableTradingAccountResult } from './rpc-disable-trading-account-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcDisconnectTradingAccountResult } from './rpc-disconnect-trading-account-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcEnableInstrumentResult } from './rpc-enable-instrument-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcEnableTradingAccountResult } from './rpc-enable-trading-account-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcError } from './rpc-error';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcGetOrderBookResult } from './rpc-get-order-book-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcGetPortfolioResult } from './rpc-get-portfolio-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcGetSystemInfoResult } from './rpc-get-system-info-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcGetTradeOrderByIdResult } from './rpc-get-trade-order-by-id-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcGetTradeOrderResult } from './rpc-get-trade-order-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcHealthCheckResult } from './rpc-health-check-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListCredentialsResult } from './rpc-list-credentials-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListInstrumentsResult } from './rpc-list-instruments-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListKlinesResult } from './rpc-list-klines-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListOrderBookSubscriptionsResult } from './rpc-list-order-book-subscriptions-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListOrderBooksResult } from './rpc-list-order-books-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListPortfoliosResult } from './rpc-list-portfolios-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListSecuritiesResult } from './rpc-list-securities-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListSubscriptionsResult } from './rpc-list-subscriptions-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListTickersResult } from './rpc-list-tickers-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListTradeOrdersResult } from './rpc-list-trade-orders-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListTradingAccountOperationsResult } from './rpc-list-trading-account-operations-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListTradingAccountSubscriptionsResult } from './rpc-list-trading-account-subscriptions-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListTradingAccountsResult } from './rpc-list-trading-accounts-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListVenuesResult } from './rpc-list-venues-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcPagination } from './rpc-pagination';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcRevokeCredentialResult } from './rpc-revoke-credential-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcRotateCredentialResult } from './rpc-rotate-credential-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSaveCredentialResult } from './rpc-save-credential-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSaveInstrumentsResult } from './rpc-save-instruments-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSaveKlinesResult } from './rpc-save-klines-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSaveOrderBooksResult } from './rpc-save-order-books-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSavePortfolioResult } from './rpc-save-portfolio-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSaveSecuritiesResult } from './rpc-save-securities-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSaveTickersResult } from './rpc-save-tickers-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSaveTradeOrderResult } from './rpc-save-trade-order-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSaveTradingAccountsResult } from './rpc-save-trading-accounts-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSubmitTradeOrderResult } from './rpc-submit-trade-order-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSubscribeOrderBookResult } from './rpc-subscribe-order-book-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSubscribeTradingAccountStreamResult } from './rpc-subscribe-trading-account-stream-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSubscription } from './rpc-subscription';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSyncInstrumentsResult } from './rpc-sync-instruments-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSyncSecuritiesResult } from './rpc-sync-securities-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcUnsubscribeOrderBookResult } from './rpc-unsubscribe-order-book-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcUnsubscribeTradingAccountStreamResult } from './rpc-unsubscribe-trading-account-stream-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcUpdateTradingAccountResult } from './rpc-update-trading-account-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcValidateTradingAccountResult } from './rpc-validate-trading-account-result';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcVerifyCredentialResult } from './rpc-verify-credential-result';

/**
 * @type WsRPCResultData
 * RPC response payload. Schema depends on the method that was called.
 */
export type WsRPCResultData = RpcCancelTradeOrderResult | RpcConnectTradingAccountResult | RpcCreateCredentialResult | RpcCreateSubscriptionResult | RpcCreateTradingAccountResult | RpcDeleteInstrumentResult | RpcDeleteSecuritiesResult | RpcDeleteTradingAccountResult | RpcDisableInstrumentResult | RpcDisableTradingAccountResult | RpcDisconnectTradingAccountResult | RpcEnableInstrumentResult | RpcEnableTradingAccountResult | RpcGetOrderBookResult | RpcGetPortfolioResult | RpcGetSystemInfoResult | RpcGetTradeOrderByIdResult | RpcGetTradeOrderResult | RpcHealthCheckResult | RpcListCredentialsResult | RpcListInstrumentsResult | RpcListKlinesResult | RpcListOrderBookSubscriptionsResult | RpcListOrderBooksResult | RpcListPortfoliosResult | RpcListSecuritiesResult | RpcListSubscriptionsResult | RpcListTickersResult | RpcListTradeOrdersResult | RpcListTradingAccountOperationsResult | RpcListTradingAccountSubscriptionsResult | RpcListTradingAccountsResult | RpcListVenuesResult | RpcRevokeCredentialResult | RpcRotateCredentialResult | RpcSaveCredentialResult | RpcSaveInstrumentsResult | RpcSaveKlinesResult | RpcSaveOrderBooksResult | RpcSavePortfolioResult | RpcSaveSecuritiesResult | RpcSaveTickersResult | RpcSaveTradeOrderResult | RpcSaveTradingAccountsResult | RpcSubmitTradeOrderResult | RpcSubscribeOrderBookResult | RpcSubscribeTradingAccountStreamResult | RpcSyncInstrumentsResult | RpcSyncSecuritiesResult | RpcUnsubscribeOrderBookResult | RpcUnsubscribeTradingAccountStreamResult | RpcUpdateTradingAccountResult | RpcValidateTradingAccountResult | RpcVerifyCredentialResult;


