/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CredentialStatus } from './credential-status';
// May contain unused imports in some cases
// @ts-ignore
import type { CredentialType } from './credential-type';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderSide } from './order-side';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderType } from './order-type';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcCancelTradeOrderParams } from './rpc-cancel-trade-order-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcConnectTradingAccountParams } from './rpc-connect-trading-account-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcCreateCredentialParams } from './rpc-create-credential-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcCreateSubscriptionParams } from './rpc-create-subscription-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcCreateTradingAccountParams } from './rpc-create-trading-account-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcDeleteInstrumentParams } from './rpc-delete-instrument-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcDeleteSecuritiesParams } from './rpc-delete-securities-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcDeleteTradingAccountParams } from './rpc-delete-trading-account-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcDisableInstrumentParams } from './rpc-disable-instrument-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcDisableTradingAccountParams } from './rpc-disable-trading-account-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcDisconnectTradingAccountParams } from './rpc-disconnect-trading-account-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcEnableInstrumentParams } from './rpc-enable-instrument-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcEnableTradingAccountParams } from './rpc-enable-trading-account-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcGetOrderBookParams } from './rpc-get-order-book-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcGetPortfolioParams } from './rpc-get-portfolio-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcGetTradeOrderByIdParams } from './rpc-get-trade-order-by-id-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcGetTradeOrderParams } from './rpc-get-trade-order-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcKline } from './rpc-kline';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListCredentialsParams } from './rpc-list-credentials-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListInstrumentsParams } from './rpc-list-instruments-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListKlinesParams } from './rpc-list-klines-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListOrderBookSubscriptionsParams } from './rpc-list-order-book-subscriptions-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListOrderBooksParams } from './rpc-list-order-books-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListPortfoliosParams } from './rpc-list-portfolios-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListSecuritiesParams } from './rpc-list-securities-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListSubscriptionsParams } from './rpc-list-subscriptions-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListTickersParams } from './rpc-list-tickers-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListTradeOrdersParams } from './rpc-list-trade-orders-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListTradingAccountOperationsParams } from './rpc-list-trading-account-operations-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListTradingAccountSubscriptionsParams } from './rpc-list-trading-account-subscriptions-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListTradingAccountsParams } from './rpc-list-trading-accounts-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcOrderBook } from './rpc-order-book';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcPagination } from './rpc-pagination';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcPortfolio } from './rpc-portfolio';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcRevokeCredentialParams } from './rpc-revoke-credential-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcRotateCredentialParams } from './rpc-rotate-credential-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSaveCredentialParams } from './rpc-save-credential-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSaveInstrumentsParams } from './rpc-save-instruments-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSaveKlinesParams } from './rpc-save-klines-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSaveOrderBooksParams } from './rpc-save-order-books-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSavePortfolioParams } from './rpc-save-portfolio-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSaveSecuritiesParams } from './rpc-save-securities-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSaveTickersParams } from './rpc-save-tickers-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSaveTradeOrderParams } from './rpc-save-trade-order-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSaveTradingAccountsParams } from './rpc-save-trading-accounts-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSubmitTradeOrderParams } from './rpc-submit-trade-order-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSubscribeOrderBookParams } from './rpc-subscribe-order-book-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSubscribeTradingAccountStreamParams } from './rpc-subscribe-trading-account-stream-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSyncInstrumentsParams } from './rpc-sync-instruments-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSyncSecuritiesParams } from './rpc-sync-securities-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcTicker } from './rpc-ticker';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcTradeOrder } from './rpc-trade-order';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcTradingAccount } from './rpc-trading-account';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcTradingAccountCredential } from './rpc-trading-account-credential';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcUnsubscribeOrderBookParams } from './rpc-unsubscribe-order-book-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcUnsubscribeTradingAccountStreamParams } from './rpc-unsubscribe-trading-account-stream-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcUpdateTradingAccountParams } from './rpc-update-trading-account-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcValidateTradingAccountParams } from './rpc-validate-trading-account-params';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcVerifyCredentialParams } from './rpc-verify-credential-params';
// May contain unused imports in some cases
// @ts-ignore
import type { SubscriptionType } from './subscription-type';
// May contain unused imports in some cases
// @ts-ignore
import type { Venue } from './venue';

/**
 * @type WsRPCRequestData
 * RPC request payload. Schema depends on the method being called.
 */
export type WsRPCRequestData = RpcCancelTradeOrderParams | RpcConnectTradingAccountParams | RpcCreateCredentialParams | RpcCreateSubscriptionParams | RpcCreateTradingAccountParams | RpcDeleteInstrumentParams | RpcDeleteSecuritiesParams | RpcDeleteTradingAccountParams | RpcDisableInstrumentParams | RpcDisableTradingAccountParams | RpcDisconnectTradingAccountParams | RpcEnableInstrumentParams | RpcEnableTradingAccountParams | RpcGetOrderBookParams | RpcGetPortfolioParams | RpcGetTradeOrderByIdParams | RpcGetTradeOrderParams | RpcListCredentialsParams | RpcListInstrumentsParams | RpcListKlinesParams | RpcListOrderBookSubscriptionsParams | RpcListOrderBooksParams | RpcListPortfoliosParams | RpcListSecuritiesParams | RpcListSubscriptionsParams | RpcListTickersParams | RpcListTradeOrdersParams | RpcListTradingAccountOperationsParams | RpcListTradingAccountSubscriptionsParams | RpcListTradingAccountsParams | RpcRevokeCredentialParams | RpcRotateCredentialParams | RpcSaveCredentialParams | RpcSaveInstrumentsParams | RpcSaveKlinesParams | RpcSaveOrderBooksParams | RpcSavePortfolioParams | RpcSaveSecuritiesParams | RpcSaveTickersParams | RpcSaveTradeOrderParams | RpcSaveTradingAccountsParams | RpcSubmitTradeOrderParams | RpcSubscribeOrderBookParams | RpcSubscribeTradingAccountStreamParams | RpcSyncInstrumentsParams | RpcSyncSecuritiesParams | RpcUnsubscribeOrderBookParams | RpcUnsubscribeTradingAccountStreamParams | RpcUpdateTradingAccountParams | RpcValidateTradingAccountParams | RpcVerifyCredentialParams | object;


