/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RpcCancelTradeOrderResponse } from './rpc-cancel-trade-order-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcConnectTradingAccountResponse } from './rpc-connect-trading-account-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcCreateCredentialResponse } from './rpc-create-credential-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcCreateSubscriptionResponse } from './rpc-create-subscription-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcCreateTradingAccountResponse } from './rpc-create-trading-account-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcDeleteInstrumentResponse } from './rpc-delete-instrument-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcDeleteSecuritiesResponse } from './rpc-delete-securities-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcDeleteTradingAccountResponse } from './rpc-delete-trading-account-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcDisableInstrumentResponse } from './rpc-disable-instrument-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcDisableTradingAccountResponse } from './rpc-disable-trading-account-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcDisconnectTradingAccountResponse } from './rpc-disconnect-trading-account-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcEnableInstrumentResponse } from './rpc-enable-instrument-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcEnableTradingAccountResponse } from './rpc-enable-trading-account-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcError } from './rpc-error';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcGetOrderBookResponse } from './rpc-get-order-book-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcGetPortfolioResponse } from './rpc-get-portfolio-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcGetSystemInfoResponse } from './rpc-get-system-info-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcGetTradeOrderByIdResponse } from './rpc-get-trade-order-by-id-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcGetTradeOrderResponse } from './rpc-get-trade-order-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcHealthCheckResponse } from './rpc-health-check-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListCredentialsResponse } from './rpc-list-credentials-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListInstrumentsResponse } from './rpc-list-instruments-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListKlinesResponse } from './rpc-list-klines-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListOrderBookSubscriptionsResponse } from './rpc-list-order-book-subscriptions-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListOrderBooksResponse } from './rpc-list-order-books-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListPortfoliosResponse } from './rpc-list-portfolios-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListSecuritiesResponse } from './rpc-list-securities-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListSubscriptionsResponse } from './rpc-list-subscriptions-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListTickersResponse } from './rpc-list-tickers-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListTradeOrdersResponse } from './rpc-list-trade-orders-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListTradingAccountOperationsResponse } from './rpc-list-trading-account-operations-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListTradingAccountSubscriptionsResponse } from './rpc-list-trading-account-subscriptions-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListTradingAccountsResponse } from './rpc-list-trading-accounts-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcListVenuesResponse } from './rpc-list-venues-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcPagination } from './rpc-pagination';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcRevokeCredentialResponse } from './rpc-revoke-credential-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcRotateCredentialResponse } from './rpc-rotate-credential-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSaveCredentialResponse } from './rpc-save-credential-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSaveInstrumentsResponse } from './rpc-save-instruments-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSaveKlinesResponse } from './rpc-save-klines-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSaveOrderBooksResponse } from './rpc-save-order-books-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSavePortfolioResponse } from './rpc-save-portfolio-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSaveSecuritiesResponse } from './rpc-save-securities-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSaveTickersResponse } from './rpc-save-tickers-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSaveTradeOrderResponse } from './rpc-save-trade-order-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSaveTradingAccountsResponse } from './rpc-save-trading-accounts-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSubmitTradeOrderResponse } from './rpc-submit-trade-order-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSubscribeOrderBookResponse } from './rpc-subscribe-order-book-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSubscribeTradingAccountStreamResponse } from './rpc-subscribe-trading-account-stream-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSubscription } from './rpc-subscription';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSyncInstrumentsResponse } from './rpc-sync-instruments-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcSyncSecuritiesResponse } from './rpc-sync-securities-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcUnsubscribeOrderBookResponse } from './rpc-unsubscribe-order-book-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcUnsubscribeTradingAccountStreamResponse } from './rpc-unsubscribe-trading-account-stream-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcUpdateTradingAccountResponse } from './rpc-update-trading-account-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcValidateTradingAccountResponse } from './rpc-validate-trading-account-response';
// May contain unused imports in some cases
// @ts-ignore
import type { RpcVerifyCredentialResponse } from './rpc-verify-credential-response';

/**
 * @type WsRPCResultData
 * RPC response payload. Schema depends on the method that was called.
 */
export type WsRPCResultData = RpcCancelTradeOrderResponse | RpcConnectTradingAccountResponse | RpcCreateCredentialResponse | RpcCreateSubscriptionResponse | RpcCreateTradingAccountResponse | RpcDeleteInstrumentResponse | RpcDeleteSecuritiesResponse | RpcDeleteTradingAccountResponse | RpcDisableInstrumentResponse | RpcDisableTradingAccountResponse | RpcDisconnectTradingAccountResponse | RpcEnableInstrumentResponse | RpcEnableTradingAccountResponse | RpcGetOrderBookResponse | RpcGetPortfolioResponse | RpcGetSystemInfoResponse | RpcGetTradeOrderByIdResponse | RpcGetTradeOrderResponse | RpcHealthCheckResponse | RpcListCredentialsResponse | RpcListInstrumentsResponse | RpcListKlinesResponse | RpcListOrderBookSubscriptionsResponse | RpcListOrderBooksResponse | RpcListPortfoliosResponse | RpcListSecuritiesResponse | RpcListSubscriptionsResponse | RpcListTickersResponse | RpcListTradeOrdersResponse | RpcListTradingAccountOperationsResponse | RpcListTradingAccountSubscriptionsResponse | RpcListTradingAccountsResponse | RpcListVenuesResponse | RpcRevokeCredentialResponse | RpcRotateCredentialResponse | RpcSaveCredentialResponse | RpcSaveInstrumentsResponse | RpcSaveKlinesResponse | RpcSaveOrderBooksResponse | RpcSavePortfolioResponse | RpcSaveSecuritiesResponse | RpcSaveTickersResponse | RpcSaveTradeOrderResponse | RpcSaveTradingAccountsResponse | RpcSubmitTradeOrderResponse | RpcSubscribeOrderBookResponse | RpcSubscribeTradingAccountStreamResponse | RpcSyncInstrumentsResponse | RpcSyncSecuritiesResponse | RpcUnsubscribeOrderBookResponse | RpcUnsubscribeTradingAccountStreamResponse | RpcUpdateTradingAccountResponse | RpcValidateTradingAccountResponse | RpcVerifyCredentialResponse;


