/* tslint:disable */
/* eslint-disable */
/**
 * Algo724 Cadenza Fermata API
 * OpenAPI Specification for Algo724 Cadenza Fermata API  ## API Resources - <a href=\"/postman-collection.json\" download=\"cadenza-postman-collection.json\">Download Postman Collection</a>
 *
 * The version of the OpenAPI document: 3.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Subscribe to a channel for real-time updates
 */
export interface WsSubscribeRequest {
    /**
     * Channel name to subscribe to
     */
    'channel': string;
    /**
     * Subscription token (for private channels)
     */
    'token'?: string;
    /**
     * Whether to recover missed messages
     */
    'recover'?: boolean;
    /**
     * Stream epoch for recovery
     */
    'epoch'?: string;
    /**
     * Stream offset for recovery
     */
    'offset'?: number;
    /**
     * Custom subscription data
     */
    'data'?: { [key: string]: any; };
    /**
     * Whether to receive position info in publications
     */
    'positioned'?: boolean;
    /**
     * Whether the subscription should be recoverable
     */
    'recoverable'?: boolean;
    /**
     * Whether to receive join/leave messages
     */
    'joinLeave'?: boolean;
    /**
     * Delta compression mode
     */
    'delta'?: string;
}

